port-labs/ocean

changelog/PORT-4306.bugfix.md
port_ocean/clients/port/client.py
port_ocean/clients/port/utils.py
port_ocean/core/event_listener/factory.py
port_ocean/core/event_listener/kafka/event_listener.py
port_ocean/core/event_listener/sample/event_listener.py
port_ocean/port_defaults.py

What - The wbhook event listener didnt work
Why - There used to be a check in the event listener factory related to the kafka
How - moved it to the event listener

PORT 4302 Fixed Webhook Listener

---

CHANGELOG.md
changelog/PORT-4303.improvement.md
changelog/PORT-4306.bugfix.md
changelog/PORT-4328.bugfix.md
changelog/PORT-4337.improvement.md
changelog/PORT-4341.bugfix.md
changelog/PORT-4343.bugfix.md
changelog/PORT-4346.breaking.md
pyproject.toml

bump ocean to 0.1.1

---

integrations/gitlab/.port/spec.yaml
integrations/gitlab/CHANGELOG.md
integrations/gitlab/changelog/v0.1.2.bump.md
integrations/gitlab/poetry.lock
integrations/gitlab/pyproject.toml

Bump gitlab v0.1.2

---

integrations/gitlab/.port/spec.yaml
integrations/gitlab/changelog/PORT-4380.improvement.md
integrations/gitlab/poetry.lock
integrations/gitlab/pyproject.toml

Gitlab 0.1.5

---

deployment/terraform/aws/ecs/examples/gitlab/main.tf
deployment/terraform/aws/ecs/main.tf
deployment/terraform/aws/ecs/modules/ecs_lb/outputs.tf
deployment/terraform/aws/ecs/modules/ecs_service/main.tf
deployment/terraform/aws/ecs/modules/ecs_service/variables.tf
deployment/terraform/aws/ecs/variables.tf

What - The ecs didnt use the correct security group
Why - The elb outputed incorrect values
How - outputing the correct values

Fix terraform security groups

---

.github/workflows/release-integrations.yml
integrations/pagerduty/.port/spec.yaml

bump version of pagerduty

---

changelog/1.bugfix.md
changelog/1.improvement.md
port_ocean/cli/commands/sail.py
port_ocean/config/base.py
port_ocean/run.py

Port 4484 change ocean sail default log level

---

port_ocean/core/handlers/port_app_config/models.py

Move Resource Config Selector to be accessible for inheritance

---

integrations/azure/.port/spec.yaml
integrations/azure/CHANGELOG.md

[Azure Integration] Fix subscriptionId description in `spec.yaml`

---

integrations/azure/.port/spec.yaml
integrations/azure/CHANGELOG.md

[BugFix][Integration][Azure] Add `event_grid_event_filter_list` and `event_grid_system_topic_name` to `spec.yaml`

---

docs/framework-guides/docusaurus.config.js
docs/framework-guides/src/components/Integrations/index.tsx

fixed integration component and removed imports

---

docs/framework-guides/docs/getting-started/getting-started.md
docs/framework-guides/docs/ocean-overview.md
docs/framework-guides/docusaurus.config.js

Fix some docs comments
What -
Why -
How -

PORT-4591 Update search provider

---

integrations/azure/.port/spec.yaml
integrations/azure/README.md

Azure fix naming of passed parameter to terraform deployment

---

integrations/gitlab/changelog/1.bugfix.md
integrations/gitlab/changelog/1.improvement.md
integrations/gitlab/gitlab_integration/core/entities.py
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/pyproject.toml

Gitlab gitops fix

---

changelog/blueprints-to-rollback.bugfix.md
changelog/include-falsy-jq-evaluate.bugfix.md
port_ocean/core/defaults/initialize.py
port_ocean/core/handlers/entity_processor/jq_entity_processor.py

Bug fixes cherry pick from snyk integration

---

CHANGELOG.md
changelog/1.bugfix.md
changelog/1.improvement.md
changelog/2.improvement.md
changelog/3.improvement.md
changelog/PORT-4483.improvement.md
changelog/PORT-4616.deprecation.md
changelog/PORT-4616.feature.md
changelog/PORT-4619.feature.md
changelog/blueprints-to-rollback.bugfix.md
changelog/include-falsy-jq-evaluate.bugfix.md
pyproject.toml

Build changelog and bump version

---

integrations/snyk/Makefile

Added install all target

---

integrations/newrelic/README.md

Update README.md - apiKey in New Relic as a secret instead of config

---

integrations/pagerduty/poetry.lock
integrations/pagerduty/pyproject.toml

Bumped pagerduty ocean version

---

integrations/newrelic/CHANGELOG.md
integrations/newrelic/newrelic_integration/ocean.py
integrations/newrelic/poetry.lock
integrations/newrelic/pyproject.toml

[Integrations][NewRelic] Support ocean >2.0, by returning a generator of list of items

---

CHANGELOG.md
changelog/PORT-4813.bugfix.md
integrations/jira/config.yaml
port_ocean/clients/port/mixins/blueprints.py
port_ocean/core/defaults/initialize.py
pyproject.toml

Add user-agent for blueprints route

---

docs/framework-guides/docs/develop-an-integration/integration-configuration.md

PORT-4846 Fix typo in integration configuration

---

integrations/newrelic/.port/resources/port-app-config.yaml
integrations/newrelic/CHANGELOG.md
integrations/newrelic/newrelic_integration/core/entities.py
integrations/newrelic/newrelic_integration/core/errors.py
integrations/newrelic/newrelic_integration/core/issues.py
integrations/newrelic/newrelic_integration/ocean.py
integrations/newrelic/pyproject.toml

[Integrations][NewRelic] Fix not handling a failure of getting related entity guid for an alert 

---

integrations/kafka/README.md

Fix kafka helm chart command in readme

fix kafka readme

---

integrations/kubecost/config.yaml

Add scheduledResyncInterval and initializePortResources to kubecost

updated kubecost config.yaml

---

integrations/kubecost/.port/resources/blueprints.json
integrations/kubecost/.port/spec.yaml
integrations/kubecost/CHANGELOG.md
integrations/kubecost/pyproject.toml
integrations/opencost/.port/resources/blueprints.json
integrations/opencost/.port/spec.yaml
integrations/opencost/CHANGELOG.md
integrations/opencost/pyproject.toml

Added kubecost & opencost icons

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/git_integration.py
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/gitlab_integration/ocean.py
integrations/gitlab/pyproject.toml

[Integration][Gitlab] Add support for project languages

---

integrations/jira/.port/resources/port-app-config.yaml
integrations/jira/CHANGELOG.md
integrations/jira/changelog/1.improvement.md
integrations/jira/pyproject.toml

Changed the default JQL to use status != Done

Added changelog

---

integrations/azure/CHANGELOG.md
integrations/azure/azure_integration/ocean.py
integrations/azure/azure_integration/utils.py
integrations/azure/pyproject.toml

What - Added azure delete resources capability when receiving delete event
Why - Until now we went with the thought that we can't know what is the identifier that the user chose for its resources ( e.g if the user change the way the default identifier in the template is configured ) so we chose not to try to delete the resource
How - In this feature I've added best effort to try to delete the resource with the default identifier

[Integration][Azure] Add "Best Effort" delete resources on delete event 

---

integrations/jira/CHANGELOG.md
integrations/jira/jira/client.py
integrations/jira/pyproject.toml

What - Use dedicated base auth function, Extract generate base params function ,Add warning messages when querying 0 results from Jira API
Why - Better usability and troubleshooting
How - Update client.py code

PORT-5708 Some updates to Jira client

---

.github/workflows/sonarcloud-framework.yml
.github/workflows/sonarcloud-integrations.yml
integrations/argocd/sonar-project.properties
integrations/azure/sonar-project.properties
integrations/firehydrant/sonar-project.properties
integrations/gitlab/sonar-project.properties
integrations/jenkins/sonar-project.properties
integrations/jira/sonar-project.properties
integrations/kafka/sonar-project.properties
integrations/kubecost/sonar-project.properties
integrations/newrelic/sonar-project.properties
integrations/opencost/sonar-project.properties
integrations/opsgenie/sonar-project.properties
integrations/pagerduty/sonar-project.properties
integrations/sentry/sonar-project.properties
integrations/servicenow/sonar-project.properties
integrations/snyk/sonar-project.properties
integrations/sonarqube/sonar-project.properties
integrations/terraform-cloud/sonar-project.properties
port_ocean/sonar-project.properties

What - Added sonarcloud analysis for Ocean framework and integrations
Why - To achieve better security, maintainability and clean code
How -

Added sonar CI for framework and integs

---

integrations/jenkins/.port/spec.yaml

Specify the docs for the integration
Add link to the integration documentation in `.port/spec.yaml`

Update Jenkins Integration spec.yaml

---

.github/workflows/create-new-sonarcloud-project.yml

What - Fixed main branch for project + fixed project ID on creation
Why -
How -

changed main branch to 'main' for default sonarcloud projects

---

integrations/jenkins/CHANGELOG.md
integrations/jenkins/pyproject.toml

followup of #358 
What - actually bump the version
Why - we missed bumping the version in the #358 fix
How -

[Integration][Jenkins] Bump version to 0.1.2

---

integrations/sonarqube/.port/resources/blueprints.json
integrations/sonarqube/CHANGELOG.md
integrations/sonarqube/pyproject.toml

What - Added aggregation properties to calculate the number of open critical issues and open issues
Why - To improve onboarding
How -

[Integration][SonarQube] Add aggregation properties to SonarQube Project

---

CHANGELOG.md
changelog/1.bugfix.md
port_ocean/core/handlers/entity_processor/jq_entity_processor.py
pyproject.toml

What - A failure in the entity processing step might fail the whole resync
Why - The error handling was moved
How - Changed the way the entity processor handled tasks

Port 7003 ocean failure in the entity processing is failing the resync

---

integrations/azure-devops/.port/spec.yaml
integrations/azure-devops/README.md

What - Updated readme and spec yaml
Why - For docs
How - changed relevant files

docs(azure-devops): update readme

---

.github/PULL_REQUEST_TEMPLATE.md

What - Add sections of screenshots and api documentation for new integrations
Why - To provide more context to the reviewer of the PR
How -

[Infra] Add new sections to pr templates

---

docs/framework-guides/docs/ocean-overview.md

What - Changed thumbnail url path in `ocean-overview.md`

changed thumbnail url path in `ocean-overview.md`

---

docs/framework-guides/docs/ocean-overview.md

What - Updated thumbnail of `ocean-overview.md` to pull image from AWS

Updated thumbnail of `ocean-overview.md` (#426)

---

integrations/jira/.port/resources/blueprints.json
integrations/jira/.port/resources/port-app-config.yaml
integrations/jira/CHANGELOG.md
integrations/jira/pyproject.toml

What - Update the default blueprints and mapping for the Jira integration, to also ingest issue labels
Why - To bring more common information out of the box
How - Reference the labels field from the issue response JSON

Update default blueprints and mapping

---

integrations/azure/.port/spec.yaml
integrations/azure/CHANGELOG.md
integrations/azure/pyproject.toml

[Integrations][Azure] Update default permissions 

---

integrations/launchdarkly/.port/spec.yaml
integrations/launchdarkly/CHANGELOG.md
integrations/launchdarkly/pyproject.toml

What - The integration was specified in the section of project management, its should be under the feature management section in the UI

[Integrations][Launchdarkly] Move to Feature Management section

---

integrations/azure/.port/resources/blueprints.json
integrations/azure/.port/resources/port-app-config.yaml
integrations/azure/CHANGELOG.md
integrations/azure/pyproject.toml

What -Fixed blueprints identifiers names and adjusted relations between blueprints
Why - To match conventions

[Integration][Azure] Fix blueprint identifiers and relation mappings

---

integrations/terraform-cloud/.port/spec.yaml

What - Fixed a link to docs in Terraform cloud integration
Why - The link was not the right one
How - Changed the link

Fixed the link

---

integrations/azure/.port/resources/blueprints.json
integrations/azure/CHANGELOG.md
integrations/azure/pyproject.toml

[Integration][Azure] Fix azureSubscription relation in resource group blueprint

---

CHANGELOG.md
port_ocean/context/event.py
pyproject.toml

What - Fix parent event context override copy typo

[Framework] Fix parent event context override copy typo

---

integrations/azure-devops/.port/resources/port-app-config.yaml
integrations/azure-devops/CHANGELOG.md
integrations/azure-devops/pyproject.toml

What - Fixed case where identfiers can have a space
Why - IngestionErrors for these kind of identifiers
How - Added regex to remove spaces
[Provide links to the API documentation used for this integration.](https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/)

Fixed spaces in identifiers

---

integrations/pagerduty/.port/resources/blueprints.json
integrations/pagerduty/.port/resources/port-app-config.yaml
integrations/pagerduty/CHANGELOG.md
integrations/pagerduty/changelog/0.1.57.improvement.md
integrations/pagerduty/pyproject.toml

Added priority and description to PagerDuty incident blueprint
What -
Why -
How -

[Integration][PagerDuty] - Add priority and description to incident

---

integrations/pagerduty/.port/resources/blueprints.json
integrations/pagerduty/.port/resources/port-app-config.yaml
integrations/pagerduty/CHANGELOG.md
integrations/pagerduty/changelog/0.1.59.improvement.md
integrations/pagerduty/pyproject.toml

What - We want to know the number of escalation levels per service
Why -
How - Counted the number of unique escalation levels in the oncall data
Sample oncall data
```{
"__oncall_user":[
{
"escalation_policy":{
"id":"ID",
"type":"escalation_policy_reference",
"summary":"Backend incident policy"
},
"escalation_level":1,
"schedule":null,
"user":{
"name":"Moris",
"email":"moris@gmail.com"
},
"start":null,
"end":null
},
{
"escalation_policy":{
"id":"ID",
"type":"escalation_policy_reference",
"summary":"Backend incident policy"
},
"escalation_level":2,
"schedule":null,
"user":{
"name":"User 2",
"email":"user2@gmail.com"
},
"start":null,
"end":null
},
{
"escalation_policy":{
"id":"ID",
"type":"escalation_policy_reference", …
```

[Integration][PagerDuty] - Add Escalation Level

---

integrations/argocd/.port/resources/blueprints.json
integrations/argocd/CHANGELOG.md
integrations/argocd/changelog/0.1.48.improvement.md
integrations/argocd/pyproject.toml

What - Updated Image icon from AWS to Docker
Why -
How -

[Integration][ArgoCD] - Updated Image Icon

---

.github/workflows/release-integrations.yml

…ifest to s3 along with existing index file
What - Changed release workflow to also push each specific integration's manifest
Why - allow easy validations in upcoming ocean Saas

Changed release workflow to also push each specific integration's manifest

---

integrations/gcp/CHANGELOG.md
integrations/gcp/gcp_core/search/resource_searches.py
integrations/gcp/pyproject.toml

What - Fixed single resource fetching issues
Why - Ids weren't parsed properly
How - Fixed ID parsing

[Integrations][GCP] Fix single resource fetching

---

integrations/gcp/.port/spec.yaml
integrations/gcp/CHANGELOG.md
integrations/gcp/pyproject.toml

What - Changed TF Variables names
Why - More readability and ease of use
How - Renames
https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/cloud-providers/gcp/

[PORT-8114] [GCP] Changed TF variables names for readability

---

pyproject.toml

What - bump ocean version in toml to 0.5.21

bump ocean version in toml

---

deployment/terraform/aws/ecs/providers.tf

Upgrade AWS version to be not hardcoded to 5 explictly

---

integrations/aws/.port/spec.yaml

What - Add deploymentMethodOverride to show in UI
Why - AWS Ocean Terraform Installation
How -

feat: add aws deploymentMethodOverride

---

.github/workflows/lint.yml

What - divide CI lint steps
Why - it's hard to see the errors on lint stage because of all the installation logs
How - dividing the steps

ci: divide steps

---

docs/framework-guides/docs/develop-an-integration/integration-spec-and-default-resources.md
integrations/azure/.port/resources/blueprints.json
integrations/azure/.port/spec.yaml
integrations/azure/CHANGELOG.md
integrations/azure/pyproject.toml
integrations/gcp/.port/resources/blueprints.json
integrations/gcp/.port/spec.yaml
integrations/gcp/CHANGELOG.md
integrations/gcp/pyproject.toml
integrations/servicenow/.port/resources/blueprints.json
integrations/servicenow/CHANGELOG.md
integrations/servicenow/pyproject.toml

[Integrations][Azure][GCP][ServiceNow] Fix default `Service` icon to `Microservice` 

---

integrations/aws/sonar-project.properties

What - Add missing config file to AWS integration
Why - it wil not deploy my integration if I won't
How - add the file

feat: Add config file to AWS integration

---

integrations/aws/CHANGELOG.md
integrations/aws/pyproject.toml

What - Bump version to deploy new version
Why - the old version was named in the same name by mistake
How -

fix: bump version

---

CHANGELOG.md
port_ocean/core/integrations/mixins/sync_raw.py
pyproject.toml

What - fixed unpacking error in register_raw

[Framework] Fixed unpacking error in register_raw

---

port_ocean/core/handlers/entity_processor/jq_entity_processor.py

What - Fix file format
Why - lint failed in production
How -

fix: file format

---

integrations/aws/CHANGELOG.md
integrations/aws/pyproject.toml
integrations/aws/utils/resources.py

What - Run all single describe in parallel
Why - sync resources will run way faster
How - use `asyncio.gather`

feat: run all single describe in parallel

---

integrations/aws/CHANGELOG.md
integrations/aws/main.py
integrations/aws/pyproject.toml
integrations/aws/utils/misc.py
integrations/aws/utils/resources.py

- **feat: add backwards compatible aws kinds**
- **feat: support custom kinds single updates**
- **fix: python bug object default as parameter**
- **refactor: rename function**
- **fix: aws rate-limit issue**
What - Multiple of issues fixed in AWS integration
Why - the integration had a couple of known bugs that were fixed in this PR
list of issue:
- missing backwards compatible kinds
- NextToken is not valid bug
- aws rate-limit issues

PORT 8694 aws integration custom aws kinds backwards compatibility

---

CHANGELOG.md

What - fix changelog date
Why -
How -

Fix changelog date search relation

---

integrations/sentry/CHANGELOG.md
integrations/sentry/clients/sentry.py
integrations/sentry/main.py
integrations/sentry/pyproject.toml

[Integration][Sentry] Reduce number of concurrent requests to fetch issue tags to avoid rate limiting

---

integrations/statuspage/pyproject.toml

Fix the release process due to invalid casing

[Integration][Statuspage] Fix casing for statuspage integration

---

integrations/datadog/.port/resources/blueprints.json
integrations/datadog/.port/resources/port-app-config.yaml
integrations/datadog/CHANGELOG.md
integrations/datadog/client.py
integrations/datadog/main.py
integrations/datadog/overrides.py
integrations/datadog/pyproject.toml
integrations/datadog/utils.py
port_ocean/core/handlers/entity_processor/jq_entity_processor.py

What - Added support to fetch history of slo histories by timeframe and how far back
Why -
How -

[Integration][Datadog] Add support to fetch history of slo history

---

integrations/azure-devops/.port/spec.yaml
integrations/azure-devops/CHANGELOG.md
integrations/azure-devops/pyproject.toml
integrations/jenkins/.port/spec.yaml
integrations/jenkins/CHANGELOG.md
integrations/jenkins/pyproject.toml
integrations/statuspage/.port/spec.yaml
integrations/statuspage/CHANGELOG.md
integrations/statuspage/pyproject.toml
integrations/wiz/.port/spec.yaml
integrations/wiz/CHANGELOG.md
integrations/wiz/pyproject.toml

Update descriptions
- Jenkins
- Wiz
- Azure Devops
- Statuspage

Port 9118 ocean Add description for missing integration properties

---

integrations/servicenow/.port/spec.yaml
integrations/servicenow/CHANGELOG.md
integrations/servicenow/changelog/0.1.44.improvement.md
integrations/servicenow/pyproject.toml

[Integration][ServiceNow] - Add description to variables

---

integrations/opsgenie/.port/spec.yaml
integrations/opsgenie/CHANGELOG.md
integrations/opsgenie/changelog/0.1.56.improvement.md
integrations/opsgenie/pyproject.toml

[Integration][Opsgenie] - Add description to variables

---

integrations/newrelic/.port/spec.yaml
integrations/newrelic/CHANGELOG.md
integrations/newrelic/changelog/0.1.58.improvement.md
integrations/newrelic/pyproject.toml

[Integration][NewRelic] - Add description to variables

---

integrations/launchdarkly/.port/spec.yaml
integrations/launchdarkly/CHANGELOG.md
integrations/launchdarkly/pyproject.toml

What - Added description to variables in spec.yaml

[Integration][Launchdarkly] - Added description to configuration properties

---

integrations/argocd/.port/spec.yaml
integrations/argocd/CHANGELOG.md
integrations/argocd/pyproject.toml

What - Added description to properties in spec.yaml

[Integration][ArgoCD] - Added descriptions to configuration properties

---

integrations/terraform-cloud/.port/spec.yaml
integrations/terraform-cloud/CHANGELOG.md
integrations/terraform-cloud/pyproject.toml

What - Added description to properties in spec.yaml

[Integration][Terraform] - Added description to configuration properties

---

.github/workflows/validate-integration-files.yml

What - Fixed Icons not being loaded properly in CI
Why - Was relying on old format
How - Change pathing

[Github-CI] Fixed CI for changing icons

---

.github/workflows/validate-integration-files.yml

What - Fixed ci of icons
Why - Didnt have system and general icons
How - 

[Github CI] Fixed validate files icon job

---

integrations/aws/CHANGELOG.md
integrations/aws/pyproject.toml
integrations/aws/utils/resources.py

What - Add logs to indicate how many entities were fetched in resync
Why - Better visibility and understanding on what is going on in each resync 
How -

[Integration][AWS] Add logs to indicate how many entities were fetched in resync

---

integrations/kubecost/CHANGELOG.md
integrations/kubecost/main.py
integrations/kubecost/pyproject.toml

Small bugfix for missing property in kubecost

Fix missing cloudCost property

---

docs/framework-guides/src/components/Integrations/index.tsx

What - Fixed integration icons in docs
Why - Was changed due to new structure
How - Fixed index.tsx icon parsing

[Docs] Fixed integration icons in docs

---

integrations/azure-devops/.port/resources/blueprints.json
integrations/azure-devops/.port/resources/port-app-config.yaml
integrations/azure-devops/CHANGELOG.md
integrations/azure-devops/pyproject.toml

[Integration][ADO] Fix property visibility mapping

---

integrations/argocd/README.md

[ArgoCD][Integration] - Update broken docs link

---

integrations/sonarqube/CHANGELOG.md
integrations/sonarqube/changelog/0.1.70.bugfix.md
integrations/sonarqube/client.py
integrations/sonarqube/pyproject.toml

What - The integration was throwing a NoneType Error when it receives a resync event for the saas_analysis/analysis kind
Why - This error error is thrown because the activity_feed/list endpoint which we rely on to fetch the analysis data does not have pagination object
How - Added a check in the get_paginated_resource to handle instances where there is no paging object from the API
Sample response from the activity_feed/list (Internal API)
```json
{
"activityFeed":[
{
"type":"analysis",
"createdAt":"2024-07-21T07:53:50.566Z",
"data":{
"analysisId":"AZDUSQHW0kVj6ncDpmU2",
"firstAnalysis":false,
"measures":{
"violations_added":"0", …
```

[Integration][SonarQube] -  Fix SonarCloud analysis bug

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/pyproject.toml

What - Search gitops file paths recursively
Why - To be able to fetch recursive gitops spec paths
How - Use python-gitalb's recursive flag when fetching repo tree

Search gitops file paths recursively

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/pyproject.toml

What - Search gitops file paths in all repo tree

[Integrations][Gitlab] Port 9343 bug git lab git ops specpath

---

CHANGELOG.md
port_ocean/core/integrations/mixins/sync_raw.py
pyproject.toml

What - Not showing misleading error message if port state is empty

[Framework] Not showing misleading error message if port state is empty

---

.github/workflows/release-integrations.yml
integrations/gitlab/pyproject.toml

What - Release spec for each version
Why - Support in versioning and infra for allowing api breakage
S3 structure before:
S3 structure after:

[CI] Release spec for each version

---

CHANGELOG.md
port_ocean/clients/port/mixins/blueprints.py
port_ocean/core/defaults/common.py
port_ocean/core/defaults/initialize.py
pyproject.toml

What - Change Defaults Action CREATE route to new actions
Why - Deprecation of v1
How - Change route and expected format of actions.json file

[Core][Port-9473] Migrate to actions v2

---

integrations/gitlab/.port/resources/actions.json
integrations/gitlab/CHANGELOG.md
integrations/gitlab/pyproject.toml

What - Changed actions.json to support new actions v2 format
Why - v1 deprecation
How - 

[Gitlab][PORT-9473] Migrated gitlab to actions v2

---

integrations/kubecost/CHANGELOG.md
integrations/kubecost/changelog/0.1.68.bugfix.md
integrations/kubecost/main.py
integrations/kubecost/pyproject.toml

What - Fixed NoneType error when fetching cloudcost data
Why -
How -

[Integration][Kubecost] Kubecost integration fetch data error

---

integrations/pagerduty/.port/resources/blueprints.json
integrations/pagerduty/CHANGELOG.md
integrations/pagerduty/pyproject.toml

Rebased update to https://github.com/port-labs/ocean/pull/822

Change PagerDuty created_at title to Created At

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/pyproject.toml

What - 
- Fix still processing a file larger than the allowed size
- Added more verbosity to the file kind
Why -
How -

[Gitlab] Fix still processing a file larger than the allowed size

---

CHANGELOG.md
port_ocean/clients/port/mixins/entities.py
pyproject.toml

Why - Integrations not ingesting data

[Framework] Remove entity key from upsert entity response

---

.github/PULL_REQUEST_TEMPLATE.md

What - Updated PR templates
Why - To make sure that tests and validation are being performed
How -

[CI] Update pr templates

---

CHANGELOG.md
pyproject.toml

Bump core to 0.10.5 - Test improvements

Bump core to 0.10.5

---

integrations/gcp/CHANGELOG.md
integrations/gcp/pyproject.toml

bumped version

---

port_ocean/middlewares.py

What - Changed logs for "Request for x" to be leveled by if its docs or not
Why - Have verbosity when needed
How - Added if and logged by condition

[Core] Changed logs to not have info by default

---

.github/workflows/release-integrations.yml

What - 
Follow up on https://github.com/port-labs/ocean/actions/runs/10703112519/job/29672916028 
Fixes - 
```
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/port-labs/port-ocean-azure:0.1.88: unexpected status from POST request to https://ghcr.io/v2/port-labs/port-ocean-azure/blobs/uploads/: 429 Too Many Requests
```

[CI] Limit release integration `max-parallel` to 15 to avoid rate limits from ghcr.io

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/gitlab_integration/ocean.py
integrations/gitlab/pyproject.toml

What - fixed case where no tasks should be ran and that raised an exception + didn't return any empty list of projects
Why - make more readable and avoid bug
How - if cases

[Gitlab] Added cases where no tasks should be ran together + empty pages of projects

---

integrations/azure-devops/CHANGELOG.md
integrations/azure-devops/azure_devops/client/azure_devops_client.py
integrations/azure-devops/pyproject.toml

What - Modified the API such that no more than 20k work items can be returned per project. This PR is necessary because ADO has a hard limit of 20k work items per API request. Also, from a product perspective, we want to allow users to use the `wiql` parameter to filter their work items so that only relevant work items (such as ACTIVE work items) can be ingested to Port.
Why - We don't want users to have huge entites in Port
How - Updated the POST /work items API to include a `$top` query parameter
Provide links to the API …

[Integration][ADO] -  Ensure that no more than 20,000 work items are returned per project

---

.github/workflows/release-integrations.yml

What - Fix a bash syntax error in the integrations release script

Fix integration release script

---

integrations/fake-integration/pyproject.toml

Bump fake integration

---

CHANGELOG.md
pyproject.toml

Bump to 0.10.11

---

integrations/_infra/Dockerfile
integrations/_infra/init.sh

What - Change our base docker image
Why - Improve security vulnerabilities and reduce docker image file size
`702MB` => `192MB` for the Fake integration

Multistep docker and move to alpine

---

.github/workflows/test.yml

Skip smoke tests until we fix both secret handling and cleanup robustness

Skip smoke tests

---

integrations/sonarqube/CHANGELOG.md
integrations/sonarqube/client.py
integrations/sonarqube/pyproject.toml

What - The integration crashes when it encounters a 400 or 404 errors. This PR handles it properly by logging the error while returning the accumulated resources instead of crashing
Why - In the event there is a 400 or 404 error in one of the API calls made to SonarQube, the whole resync event for kind does not get synced.
How -

[Integration][SonarQube] - Handle 4xx errors gracefully

---

.github/workflows/docker-images-security-scan.yml

Add `trivy` docker image scanner

PORT 9979 docker image security scanner workflow

---

CHANGELOG.md
pyproject.toml

What - Decided to bump to 0.11.0 instead of 0.10.13 as it is a major change
Why -
How -

Bump to 0.11.0

---

integrations/servicenow/.port/resources/blueprints.json

What - updated icons for servicenow blueprints
Why - so the proper icons are used
How -
- [x ] Non-breaking change (fix of existing functionality that will not change current behavior)

[Integration][ServiceNow] Updated icons for servicenow blueprints

---

.github/workflows/core-test.yml
.github/workflows/detect-changes-matrix.yml
Makefile
integrations/_infra/Dockerfile
integrations/_infra/init.sh
port_ocean/log/sensetive.py
port_ocean/tests/helpers/fixtures.py
port_ocean/tests/helpers/integration.py
port_ocean/tests/helpers/port_client.py
port_ocean/tests/helpers/smoke_test.py
port_ocean/tests/test_smoke.py
pyproject.toml
scripts/clean-smoke-test.py
scripts/run-smoke-test.sh

What - Move our docker images to alpine instead of debian
Why - Security vulnerabilities and docker image size
In addition, improve smoke test stability

Move to alpine instead of debian and improve smoke test

---

CHANGELOG.md
integrations/_infra/Dockerfile
integrations/_infra/init.sh
port_ocean/core/handlers/entity_processor/jq_entity_processor.py
port_ocean/tests/core/handlers/entity_processor/test_jq_entity_processor.py
pyproject.toml

What -  Fixed `StopIteration` error which was happening with the new jq.py package where trying to get a value from a an empty list using iterator caused the thread to stop and thus the whole resync to stuck
```
Exception in callback <function _chain_future.<locals>._set_state at 0x10678ed40>
handle: <Handle _chain_future.<locals>._set_state>
Traceback (most recent call last):
File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
File "/Users/tomtankilevitch/.pyenv/versions/3.11.4/lib/python3.11/asyncio/futures.py", line 383, in _set_state
_copy_future_state(other, future)
File "/Users/tomtankilevitch/.pyenv/versions/3.11.4/lib/python3.11/asyncio/futures.py", line 359, in _copy_future_state
dest.set_exception(_convert_future_exc(exception))
TypeError: StopIteration interacts …
```

[Core] Fix stop iterator bug in jqpy

---

CHANGELOG.md

What - Fix miscalculated changelog version step 0.12.1 -> ~0.12.12~ 0.12.2 
Why -
How -

[Core] | Fix Changelog Version Step

---

port_ocean/cli/commands/new.py
port_ocean/cli/cookiecutter/hooks/post_gen_project.py
port_ocean/tests/helpers/fixtures.py
port_ocean/tests/helpers/ocean_app.py
scripts/run-smoke-test.sh

What - Improve the `ocean new` command
Why - Solve bugs

Fix missing make file and bugs in new command

---

integrations/backstage/.port/spec.yaml
integrations/backstage/CHANGELOG.md
integrations/backstage/pyproject.toml

What - Changed category to others
Why - Product request

[Integrations][Backstage] Changed backstage category to others

---

integrations/backstage/CHANGELOG.md
integrations/backstage/client.py
integrations/backstage/main.py
integrations/backstage/pyproject.toml
integrations/backstage/tests/conftest.py
integrations/backstage/tests/test_sample.py
integrations/backstage/tests/test_sanity.py

Fix missing docker platform for backstage

Fix missing platform for backstage

---

CHANGELOG.md
changelog/0.12.5.bugfix.md
port_ocean/tests/helpers/ocean_app.py
pyproject.toml

What - Fixed the bug for test helper function `get_integation_resource_configs` where it doesn't handle `.yaml` extension for `port-app-config` file
Why - Most integrations do not have their `port-app-config` file as `.yml` extension and using the helper function in tests causes tests to fail
How - A check is made to see if the `.yml` path exists and if it fails, we default to the `.yaml` extension.

Bug | `get_integation_resource_configs` does not handle `.yaml` extension for `port-app-config` file

---

CHANGELOG.md
port_ocean/tests/helpers/ocean_app.py
pyproject.toml

By ensuring that the configuration goes through the default_factory

Ensure spec configuration goes through default factory

---

integrations/_infra/Dockerfile.Deb

What -  Add `openssl` certificates to image
Why - As part of separation of the images in #1079 the openssl installation was missed for the deb image 
How -

[Infra] Add `openssl` certificates to image

---

integrations/jenkins/CHANGELOG.md
integrations/jenkins/client.py
integrations/jenkins/pyproject.toml

**What** - Increase Jenkins builds fetch limit from 50 to 100 builds per job
**Why** - From a customer request in this [slack support thread](https://getport.slack.com/archives/C07TSF9TC48/p1730210539061229)
**How** - Modified the builds pagination parameter in the Jenkins API query from {0,50} to {0,100}, which is the maximum number of builds that Jenkins API allows per request.

Update to 100 builds fetched

---

CHANGELOG.md
poetry.lock
pyproject.toml

What - bump fastapi version to 0.115.3 to upgrade starlette
Why - https://github.com/port-labs/ocean/security/dependabot/433 
How - bump fastapi version

[Core] bump fastapi version

---

pyproject.toml

Update version from 0.12.8 to 0.12.9

[Core] Bump core version

---

.github/workflows/core-test.yml

Fix a typo in the GitHub action for core tests to ensure the test integration is cleaned up

[Core][CI] Fix smoke test cleanup

---

CHANGELOG.md
pyproject.toml

[Core] add changelog and bump version

---

.github/workflows/core-test.yml
.github/workflows/perf-test.yml
CHANGELOG.md
integrations/_infra/Makefile
integrations/fake-integration/.port/resources/blueprints.json
integrations/fake-integration/.port/resources/port-app-config.yml
integrations/fake-integration/.port/spec.yaml
integrations/fake-integration/fake_org_data/fake_client.py
integrations/fake-integration/fake_org_data/fake_router.py
integrations/fake-integration/fake_org_data/generator.py
integrations/fake-integration/fake_org_data/types.py
integrations/fake-integration/main.py
integrations/fake-integration/tests/test_sync.py
pyproject.toml
scripts/run-local-perf-test.sh
scripts/run-local-smoke-test.sh
scripts/run-smoke-test.sh
scripts/smoke-test-base.sh

Added a way to run the fake integration with configurable total entities count.
This allows us to gather performance metrics.

[Core] Performance measure framework

---

CHANGELOG.md
port_ocean/clients/port/authentication.py
port_ocean/tests/log/test_handlers.py
pyproject.toml

What - Added warning log
Why - To make sure we indicate that using personal tokens will lead to unwanted behaviors, including logs not being shown in the UI
How - Added log

[Core] Added warning for personal credentials

---

scripts/bump-all.sh

What -
Replace poetry search
Why -
poetry search doesn't return version
How -
Replace poetry search with pip index to get ocean latest version.

[Core] Fix `bump-all.sh` to use `pip` for finding out ocean version

---

integrations/datadog/.port/resources/blueprints.json
integrations/datadog/.port/resources/port-app-config.yaml
integrations/datadog/CHANGELOG.md
integrations/datadog/examples/blueprints.json
integrations/datadog/examples/mappings.yaml
integrations/datadog/pyproject.toml

What - Remove slo_history from default templates
Why - As incremental syncs are not supported 
How -

[Integration][Datadog] Remove `slo_history` from default templates

---

.github/workflows/apply-release.yml

What - Add prefix to pr name created by integration bump pipeline
Why - To align it with the new title conventions
How -

[CI] Add prefix to pr name created by integration bump pipeline

---

.github/workflows/apply-release.yml

Replace poetry search with pip index to get ocean latest version.
What -
Replace poetry search
Why -
poetry search doesn't return version
How -
Replace poetry search with pip index to get ocean latest version.

[Core] Fix `apply-release.yml` to use `pip` for finding out ocean version

---

integrations/fake-integration/fake_org_data/fake_client.py

Last minute refactor left some typos

[Core] Ocean perf test last rename typos

---

CHANGELOG.md
port_ocean/config/settings.py
port_ocean/core/models.py
port_ocean/ocean.py
pyproject.toml

What - Added `SaasOauth` runtime support
Why -
How -

[Core] Add `SaasOauth` runtime support

---

CHANGELOG.md
port_ocean/core/models.py
pyproject.toml

What - Change `SaasOauth` to `SaasOauth2` runtime
Why - Because Saas is passing it as `SaasOauth2`
How -

[Core] Change `SaasOauth` to `SaasOauth2` runtime

---

CHANGELOG.md
port_ocean/core/models.py
port_ocean/core/utils.py
port_ocean/tests/core/test_utils.py
pyproject.toml

[Core] Add handling for different installation types

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/pyproject.toml

What - Added project labels to the project kind response
Why -
How - Enriched the project response with `__labels` object

[Integration][GitLab] Add project labels

---

integrations/fake-integration/CHANGELOG.md
integrations/fake-integration/fake_org_data/fake_client.py
integrations/fake-integration/main.py
integrations/fake-integration/pyproject.toml

What - added webhook route
Why - load tests for realtime 
How -

[Integration] [fake integration] Added webhooks to fake integration

---

integrations/gitlab/.port/resources/blueprints.json
integrations/gitlab/.port/resources/port-app-config.yaml
integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/events/hooks/push.py
integrations/gitlab/gitlab_integration/git_integration.py
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/gitlab_integration/ocean.py
integrations/gitlab/pyproject.toml

What - Added mechanism to make the enrichment of project labels optional
Why - Not making it optional could leave to potential rate limit
How - Added an `includeLabels` param to the project kind

[Integration][GitLab] Make Project Labels Optional

---

.vscode/launch.json
CHANGELOG.md
docs/framework-guides/docs/getting-started/getting-started.md
port_ocean/cli/commands/new.py
port_ocean/cli/cookiecutter/cookiecutter.json
port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/.env.example
port_ocean/debug_cli.py
pyproject.toml

fixed the flow of the ocean new command since it was not working properly by getting all data needed from the user and filling it out for him, and added debug file 

[Core] Extend ocean new cli command

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/pyproject.toml
integrations/jira/.port/spec.yaml

What - set jira oauth integration to minimum of 2hr resync schedules
Why - to match Jira's token invalidation's strategy 
How - set jira oauth integration to minimum of 2hr resync schedules in spec file

[Integration][Jira] set jira oauth integration to minimum of 2hr resync schedules

---

integrations/pagerduty/.port/spec.yaml
integrations/pagerduty/CHANGELOG.md
integrations/pagerduty/clients/pagerduty.py
integrations/pagerduty/pyproject.toml

What:
- Added support for OAuth2.0 token
- Added OAuth installation specification for Port

[Integration][Pagerduty] Port 12076 pagerduty oauth support

---

CHANGELOG.md
port_ocean/context/ocean.py
port_ocean/core/integrations/mixins/events.py
pyproject.toml

What - lint fix
Why - pipeline fails for two resync kinds on one resource
How - add none as possible value

[Core] Added None type for wrapper

---

CHANGELOG.md
port_ocean/context/ocean.py
pyproject.toml

What - fixed lint error
Why - Event listener can not be sent
How - add none to type

[Core] Fixed lint

---

.vscode/launch.json
integrations/datadog/.port/spec.yaml
integrations/datadog/CHANGELOG.md
integrations/datadog/client.py
integrations/datadog/main.py
integrations/datadog/pyproject.toml

What - Introduced support for OAuth2 authentication in Datadog integration, allowing the use of an access token. also added a new launch configuration for debugging the Datadog integration.
Why - This change enhances the integration's flexibility and security by supporting OAuth2, improving the overall functionality of the Datadog integration.
How - Updated `DatadogClient` to accept an optional access token and modified authentication headers accordingly.

[Integration][Datadog] Added OAuth support for datadog

---

.github/CODEOWNERS

[Infra] changed team name in CODEOWNERS

---

.vscode/launch.json
CHANGELOG.md
port_ocean/core/defaults/initialize.py
port_ocean/core/event_listener/base.py
port_ocean/core/event_listener/http.py
port_ocean/core/event_listener/kafka.py
port_ocean/core/event_listener/once.py
port_ocean/core/event_listener/polling.py
port_ocean/core/event_listener/webhooks_only.py
pyproject.toml

What - Fixed case where integration creation failed when using WEBHOOKS_ONLY event listener + added jira vscode launch config
Why - integration creation doesn't work
How - overriding to_request

[Core] Fixed case where integration creation failed when using `WEBHOOKS_ONLY`

---

integrations/azure/CHANGELOG.md
integrations/azure/azure_integration/azure_patch.py
integrations/azure/pyproject.toml

What - Updated the `list_resources` function to set both `_config.api_version` and `_api_version` in the `ResourceManagementClient.resources` object.
Why - The `_config.api_version` alone was insufficient in ensuring consistent behavior across paginated responses and API interactions as list method defaults to the `_api_version` for 2nd iteration and beyond during iteration through paginated response. By also setting `_api_version`, the resource client uses the specified version throughout its operations, improving reliability and consistency when querying Azure resources.
How - Patched default value for `resources_client.resources._api_version`
<h4> All tests should be run against the port production environment(using a …

[Integration][Azure] Enhanced API Version Consistency in Resource Management Client

---

integrations/jira/.port/resources/port-app-config.yaml
integrations/jira/CHANGELOG.md
integrations/jira/pyproject.toml

What - Updated default mapping to use `empty` instead of `""`
Why - To deal with the issue of integration spamming parentIssue error when parentIssue is not present in the JSON
How - Updated the default mapping

[Integration][Jira] Updated default mapping

---

integrations/gitlab/.port/resources/port-app-config.yaml
integrations/gitlab/CHANGELOG.md
integrations/gitlab/pyproject.toml

What - removed description from port-app-config yaml
Why - the service blueprint does not have description property
How - deleted from the mapping

[Integration] Removed description from port-app-config yaml

---

.github/workflows/apply-release.yml
.github/workflows/upgrade-integrations.yml

[CI] Fix poetry version to use `1.8.3`

---

docs/framework-guides/docs/_common/resync-abort-message.mdx
docs/framework-guides/docs/develop-an-integration/integration-configuration.md

What - Update notes about scheduled resync interval flag
Why - For clarity
How - Small updates

[Docs] PORT-12872 Update notes about scheduled resync interval flag

---

integrations/aws/pyproject.toml

What -This PR fixes a mistakenly committed an rc version in pyproject

[Integration][AWS] Fix integration version in pyproject

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/events/event_handler.py
integrations/gitlab/pyproject.toml

##Description
What
Currently, when a live event is received, we pass a deep copy of the event object to each observer. This was originally implemented to ensure that every observer received its own, uniquely referenced copy of the event. However, in our current workflow, observers do not modify the event data—they only use it to fetch resources from GitLab.
Why
- Since the observers only perform read operations (i.e., fetching data) and do not modify the event object, creating deep copies is redundant.
- It has been observed that the deep‑copied objects are not being garbage collected after use, which results in increased memory usage and could eventually lead to memory exhaustion.
- The deep copy operation introduces additional processing time and memory overhead that is not needed given …

[Integration][Gitlab] Fix Memory Leak Identified In Live Events Sync

---

integrations/amplication/.port/resources/actions.json
integrations/amplication/.port/resources/scorecards.json
integrations/amplication/.port/spec.yaml

[Integration] [Amplication] fixed lint 

---

integrations/jira/.port/spec.yaml
integrations/jira/CHANGELOG.md
integrations/jira/pyproject.toml

What - Enabled SaaS live events for the Jira integration
Why - SaaS support for Jira
How - Added tag in spec.yaml

[Integration][Jira] Enabled saas live events

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/pyproject.toml

**What -**  
This PR updates the asynchronous file search logic by introducing a flag (`files_found`) to track whether any matching files are yielded during iteration. If no files are found, it logs an appropriate message.
**Why -**  
Previously, the `async for...else` construct always executed the `else` block, causing a log message to be printed even when files were successfully found. The new approach ensures that the log message is only triggered when no files match the search patterns.
**How -**  
1. A boolean flag `files_found` is initialized to `False` before starting the asynchronous iteration.  
2. As files are yielded by the asynchronous generator, the flag is set to `True`.  
3. After the iteration completes, the flag is checked. If no files were found (`files_found` is still …

[Integration][Gitlab] Fix File Search Logging to only log when no files found

---

integrations/azure-devops/CHANGELOG.md
integrations/azure-devops/pyproject.toml

What - This PR bumps the ADO integration version.
Why - A conflict occurred between the last two PRs where one didn't contain a bump and merging the bumped version before the one without it may have caused the fix not to be applied
How -

[Integration][ADO] Bump integration version

---

integrations/pagerduty/.port/spec.yaml
integrations/pagerduty/CHANGELOG.md
integrations/pagerduty/clients/pagerduty.py
integrations/pagerduty/consts.py
integrations/pagerduty/kinds.py
integrations/pagerduty/main.py
integrations/pagerduty/pyproject.toml
integrations/pagerduty/tests/test_client.py
integrations/pagerduty/tests/test_webhook_processors.py
integrations/pagerduty/webhook_processors/abstract.py
integrations/pagerduty/webhook_processors/incidents.py
integrations/pagerduty/webhook_processors/services.py

What - Added webhook processors for services and incidents and turned pagerduty client async
Why - Support new standard way of live events treatment
How - Added oauth dependency + Created new webhook processing classes

[Integration][Pagerduty] Added Live events + OAuth client

---

CHANGELOG.md
port_ocean/config/settings.py
port_ocean/core/handlers/webhook/processor_manager.py
port_ocean/ocean.py
port_ocean/tests/core/handlers/webhook/test_processor_manager.py
pyproject.toml

What - Add configurable event processing timeouts to Ocean
Why - allowing different integrations to have different thresholds for timeouts
How - removed default values, entered these values to ocean core variables

[Core] Add configurable event processing timeouts to Ocean

---

CHANGELOG.md
port_ocean/core/handlers/webhook/processor_manager.py
port_ocean/core/handlers/webhook/webhook_event.py
port_ocean/tests/core/handlers/webhook/test_processor_manager.py
pyproject.toml

What -- Updated LiveEventsProcessorManager to fetch the latest port app configuration for each event.
Why - This change ensures that the processor manager always uses the most current configuration when handling events.
How - By calling `get_port_app_config(use_cache=False)` before after each event_context 

[Core] Fetch latest port app config for each event

---

docs/framework-guides/package-lock.json
docs/framework-guides/package.json

[Docs] Fix docs vulnerabilities

---

integrations/servicenow/CHANGELOG.md
integrations/servicenow/client.py
integrations/servicenow/pyproject.toml

What -
ServiceNow Intergration Sanity check
Why -
Currently the sanity check makes a sample request against /api/now/table/incident?sysparm_limit=1, which leads to problems if one is using least privilege. This causes the servicenow integration to be in a CrashLoopBackOff as the sanity check is not passed.
Change to sys_user table in ServiceNow, as this is mostly required for other action on api.

[Integration][ServiceNow] - Sanity check on a more generic api

---

docs/framework-guides/package-lock.json
integrations/gitlab-v2/.port/resources/blueprints.json
integrations/gitlab-v2/.port/resources/port-app-config.yml
integrations/gitlab-v2/CHANGELOG.md
integrations/gitlab-v2/poetry.lock
integrations/gitlab-v2/pyproject.toml

What - This PR aligns default integration defaults with existing integration defaults
Why - Align integration with existing defaults
How - Update config mapping and blueprint for project kind.

[Integration][Gitlab-v2] Align integration defaults

---

integrations/gitlab-v2/CHANGELOG.md
integrations/gitlab-v2/pyproject.toml

What - Release Beta Version of the Gitlab-V2 Integration
Why -  evaluate functionality, identify issues, and ensure stability before GA rollout.
How - Bump integration version from dev

 [Integration][Gitlab-v2] Upgrades GitLab-v2 integration from dev to beta

---

integrations/gitlab-v2/.port/spec.yaml
integrations/gitlab-v2/CHANGELOG.md
integrations/gitlab-v2/pyproject.toml

What - Fixed the icon not showing on datasource page
Why -
How -

[Integration][Gitlab-V2] Fix integration icon

---

integrations/komodor/.port/spec.yaml
integrations/komodor/CHANGELOG.md
integrations/komodor/pyproject.toml

[Integration][Komodor] Fix icon

---

integrations/bitbucket-cloud/.port/spec.yaml
integrations/bitbucket-cloud/CHANGELOG.md
integrations/bitbucket-cloud/pyproject.toml

What - Removed bitbucket from the gitops section on data source page
Why -
How - Updated the `spec.yaml` file

[Integration][Bitbucket] Removed bitbucket gitops card

---

integrations/jira/CHANGELOG.md
integrations/jira/jira/client.py
integrations/jira/pyproject.toml
integrations/jira/tests/test_client.py
integrations/jira/tests/test_processors.py
integrations/jira/webhook_processors/issue_webhook_processor.py

What - Update Jira integration to use new JQL search endpoint before May 1st, 2025 deprecation
Why - The current /rest/api/3/search endpoint will be deprecated and removed after May 1st, 2025. We need to migrate to the new /rest/api/3/search/jql endpoint to ensure continued functionality. [Deprecation Warning Link](https://developer.atlassian.com/changelog/?utm_campaign=sr_sr4jc_email_hs_ad-hoc-announcements_an_hs_aho_glob_all_en__&utm_medium=email&_hsmi=352955349&utm_source=hubspot#CHANGE-2046)
How - 
- Replace deprecated endpoint with new /rest/api/3/search/jql endpoint
- Update pagination to use nextPageToken instead of startAt
- Ensure fields parameter is always passed with *all default
- Update tests to reflect new endpoint behavior
Please leave one option from the following and …

[Integration][Jira] Migrate Jira Integration from Deprecated search Endpoint to the GA endpoint Before May 2025 Deprecation

---

integrations/wiz/CHANGELOG.md
integrations/wiz/pyproject.toml
integrations/wiz/tests/test_client.py
integrations/wiz/wiz/client.py

**What**  
This PR fixes a bug in the Wiz integration where connection errors, such as `ConnectError: [Errno -3] Temporary failure in name resolution`, were not retried during GraphQL queries. It adds a test to verify the retry behavior and updates the `make_graphql_query` method to include the `extensions={"retryable": True}` parameter.
**Why**  
The `make_graphql_query` method in `WizClient` was not configured to retry transient connection errors, leading to failures when temporary network issues occurred (e.g., DNS resolution failures). The error traceback showed a `ConnectError` during an HTTP POST request to the Wiz API, which disrupted the application's functionality. Enabling retries for such errors ensures temporary network issues do not cause unhandled exceptions.
**How**  
- …

[Integration][Wiz] Added retry mechanisim for transient error

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/gitlab_integration/gitlab_service.py
integrations/gitlab/pyproject.toml
integrations/gitlab/tests/gitlab_integration/test_gitlab_service.py

What - Fixed the Gitlab integration stripping newline character from the file content of non json/yaml file
Why - 
How - Seperated parsing based on file name so that files that are not JSON or YAML files will not be parsed

[Integration][Gitlab] Fixed the Gitlab integration stripping newline character from the file content of 

---

CHANGELOG.md
port_ocean/core/handlers/port_app_config/base.py
pyproject.toml

What - Improved logging when the port integration mapping is invalid
Why - Currently not providing any explanations as to why the mapping calculation failed
How - Add pydantic's validation error to log message

[Core] Enhanced error logging to include specific error for mappings

---

integrations/opsgenie/CHANGELOG.md
integrations/opsgenie/client.py
integrations/opsgenie/pyproject.toml
integrations/opsgenie/tests/test_client.py

This PR introduces changes to improve the OpsGenie client and its integration. It includes a safeguard for pagination limits and comprehensive test coverage.
What - 
1. Added a safeguard mechanism in the `OpsGenieClient` to respect the maximum offset limit (`MAX_OPSGENIE_OFFSET_LIMIT`) during pagination.
2. Introduced a new test suite (`test_client.py`) to validate the functionality of the `OpsGenieClient`.
Why - 
1. OpsGenie's API imposes a maximum offset limit, and exceeding it could result in errors. The safeguard ensures compliance with the API while avoiding unnecessary requests.
How - 
1. Introduced the constant `MAX_OPSGENIE_OFFSET_LIMIT` and updated the `get_paginated_resources` method to:
- Halt pagination if the offset limit is exceeded.
- Log a warning when the limit is …

[Integration][OpsGenie] Adds Pagination Limit to Prevent 422 when max offset is hit

---

CHANGELOG.md
port_ocean/clients/port/authentication.py
port_ocean/clients/port/client.py
port_ocean/clients/port/mixins/blueprints.py
port_ocean/clients/port/mixins/entities.py
port_ocean/clients/port/mixins/integrations.py
port_ocean/clients/port/mixins/migrations.py
port_ocean/clients/port/mixins/organization.py
port_ocean/clients/port/utils.py
port_ocean/tests/clients/port/mixins/test_organization_mixin.py
pyproject.toml

What - Added 500 trace id on Port 5XX errors
Why - Add visibility and tracking for issues in Port
How - Add the `x-trace-id` header's value if the error is 5XX and response has this header

[Core] Enhance error logging by including trace IDs for server errors

---

integrations/jira-server/CHANGELOG.md
integrations/jira-server/pyproject.toml
integrations/jira-server/sonar-project.properties

[Integration][Jira] Bump integration version to release image

---

CHANGELOG.md
pyproject.toml

What - Bump version
Why - Bump the version for the missing versions from the dependabot vulnerabilities 
How - Bump the core version thus bumping the integrations versions

[Core] bump version for dependabot vulnerabilities

---

integrations/jira/CHANGELOG.md
integrations/jira/jira/client.py
integrations/jira/pyproject.toml
integrations/jira/tests/test_client.py

**What**  
Added a permission check before attempting to create Jira webhooks in the `JiraClient`.
**Why**  
Previously, if the user token lacked the `ADMINISTER` permission, webhook creation would fail with a 403 error, interrupting the resync process. This update prevents such interruptions by checking permissions ahead of time.
**How**  
- Introduced a new `has_webhook_permission` method to query the Jira API for the `ADMINISTER` permission.
- Updated `create_webhooks` to skip creation and log a warning if the required permission is not present.
- Added test cases to verify webhook creation behavior when permission is granted or denied.
<h4> All tests should be run against the port production environment(using a testing …

[Integration][Jira] Add permission check before creating Jira webhooks to prevent 403 errors

---

.github/workflows/core-test.yml
CHANGELOG.md
port_ocean/core/integrations/mixins/sync_raw.py
port_ocean/core/integrations/mixins/utils.py
pyproject.toml

What -
- Add e2e tests.
Why -
- Couldnt run fake integration in e2e tests.
How -
- Release event loop while waiting for process to finish.

[Core] Multiprocessing

---

.github/workflows/docker-images-security-scan.yml

[CI] Fix Docker images scan workflow

---

integrations/jira/CHANGELOG.md
integrations/jira/jira/client.py
integrations/jira/pyproject.toml
integrations/jira/tests/test_client.py

Description
What -
This pull request updates the JiraClient class to use is_oauth_enabled instead of is_oauth_host for determining OAuth authentication mode, ensuring proper handling of OAuth based on token availability.
Why -The previous implementation relied on checking the Jira URL for "api.atlassian.com" to determine OAuth usage, which was incorrect as OAuth should be determined by the presence of an OAuth token. The change ensures correct authentication behavior and improves test reliability.
How -  
Replaced is_oauth_host with is_oauth_enabled in JiraClient to check for OAuth token availability via ocean.app.load_external_oauth_access_token().
Removed the is_oauth_host method as it’s no longer needed.
Updated test_client.py to mock load_external_oauth_access_token returning None for …

[Integration][Jira] Update OAuth Detection Logic

---

integrations/github-copilot/CHANGELOG.md
integrations/github-copilot/clients/github_client.py
integrations/github-copilot/pyproject.toml

What - Fix Pagination Bug
Why - Customer Bug
How - Sanitize the base url and the path (remove '/' from beginning and end)

[Integration][Github Copilot] Pagination Bug

---

CHANGELOG.md
port_ocean/core/integrations/mixins/sync_raw.py
port_ocean/tests/core/handlers/mixins/test_sync_raw.py
pyproject.toml

What - fixed the result returned from the sync function
Why - in order to report it correctly
How - added returns where ever needed

[Core] Fixed result of sync returned

---

CHANGELOG.md
port_ocean/core/integrations/mixins/sync_raw.py
pyproject.toml

What - Added resource kind to logging context
Why - To have better visibility on which kinds cause OOMs
How -

[Core] Added resource kind to logging context

---

integrations/gitlab/CHANGELOG.md
integrations/gitlab/pyproject.toml

What - deprecation gitlab
Why - deprecation
How - manually

[Integration][Gitlab] deprecation returned

---

integrations/backstage/CHANGELOG.md
integrations/backstage/pyproject.toml
integrations/bitbucket-server/CHANGELOG.md
integrations/bitbucket-server/pyproject.toml
integrations/fake-integration/CHANGELOG.md
integrations/fake-integration/pyproject.toml
integrations/github/CHANGELOG.md
integrations/github/pyproject.toml
integrations/gitlab/CHANGELOG.md
integrations/gitlab/pyproject.toml
integrations/jira-server/CHANGELOG.md
integrations/jira-server/pyproject.toml

- **feat: Update integration versions to beta and dev releases**
- **chore: Update changelogs to reflect version suffix changes**
What -
Why -
How -

[Integration] feat readd integrations versions tags

---

integrations/azure-devops/CHANGELOG.md
integrations/azure-devops/azure_devops/client/base_client.py
integrations/azure-devops/pyproject.toml
integrations/azure-devops/tests/azure_devops/client/test_azure_devops_base_client.py

What -
- Fixes a bug in the Azure DevOps integration where paginated API responses were not always fully retrieved for `userentitlements` due to incomplete handling of the continuation token.
- The pagination logic now correctly checks both the response headers and body for the continuation token, ensuring all pages are fetched as expected.
Why -
- Previously, the pagination method only checked for the continuation token  in the response headers (`x-ms-continuationtoken`), missing cases where Azure DevOps returns the token  in the response body.
- This could result in incomplete data retrieval, with some items/pages being skipped, leading to data inconsistency and missing entities in Port.
How -
- Updated the `_get_paginated_by_top_and_continuation_token` method to check both the response …

[Integration][azure-devops] Pagination Bug fix for Continuation Token

---

integrations/argocd/.port/spec.yaml
integrations/argocd/CHANGELOG.md
integrations/argocd/pyproject.toml
integrations/jira/.port/spec.yaml
integrations/jira/CHANGELOG.md
integrations/jira/pyproject.toml
integrations/pagerduty/.port/spec.yaml
integrations/pagerduty/CHANGELOG.md
integrations/pagerduty/pyproject.toml

What -
Why -
How -
___
Other
___
- Restructured `installationDocs` parameter from array to object format
- Updated three integrations: ArgoCD, Jira, and PagerDuty
- Changed YAML structure while preserving all configuration values
- Incremented version numbers for all affected integrations
___
```mermaid
flowchart LR
A["Array Format"] --> B["Object Format"]
B --> C["ArgoCD Integration"]
B --> D["Jira Integration"] 
B --> E["PagerDuty Integration"]
C --> F["Version …
```

[Integration] Changed structure of installationDocs param

---

CHANGELOG.md
port_ocean/config/settings.py
port_ocean/core/handlers/entity_processor/jq_entity_processor.py
port_ocean/core/integrations/mixins/sync_raw.py
port_ocean/core/integrations/mixins/utils.py
pyproject.toml

What -
Move the items to parse logic to be yielded from the generator to support ocean's logic.
Why -
Causes OOM
How -
get items to parse when the batches are yielded.
___
Enhancement
___
- Add configuration option to yield items to parse in batches
- Move items parsing logic from entity processor to generator wrapper
- Support configurable batch size for yielded items
___
```mermaid
flowchart LR
A["Configuration"] --> B["Generator Wrapper"]
B --> C["Items Parsing …
```

[Core] Yield items to parse

---

CHANGELOG.md
poetry.lock
pyproject.toml

What - bump fastapi version to 0.116.0 to upgrade starlette
Why - https://github.com/port-labs/ocean/security/dependabot/907
How - bump fastapi version
___
Bug fix
___
- Update FastAPI dependency to fix security vulnerability
___
```mermaid
flowchart LR
A["pyproject.toml"] -- "update version" --> B["FastAPI ^0.116.0"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>pyproject.toml</strong><dd><code>Update FastAPI dependency version</code>&nbsp; …

[Core] fix dependabot alert

---

integrations/aws-v3/CHANGELOG.md
integrations/aws-v3/pyproject.toml

What - Bump version and change log
Why - I forgot
How - edit changelog and pyproject file

[Integration][AWS-v3] bump version and changelog

---

.github/workflows/claude-generic.yml

What -
Why -
How -
___
Other
___
- Increase timeout for Claude AI workflow from default to 25 minutes
___
```mermaid
flowchart LR
workflow["GitHub Workflow"] -- "timeout increased" --> claude["Claude AI Action"]
claude -- "25 minutes" --> timeout["Extended Timeout"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table> …

chore: increase timeout

---

.github/workflows/claude-generic.yml

What -
Why -
How -
___
Other
___
- Add GitHub token environment variable to Claude workflow
___
```mermaid
flowchart LR
A["GitHub Workflow"] --> B["Add GITHUB_TOKEN env var"]
B --> C["Enable repository access"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details> …

chore: add permissions to claude code

---

integrations/github/CHANGELOG.md
integrations/github/github/helpers/gql_queries.py
integrations/github/pyproject.toml

What - Update the GitHub Integration to match GitHub response on User/Member Data
Why - Github docs now mentions that they return .name, .login, and .email where previously it was just .login and .email
How - Include the .name key in the graphql query in the affected exporters
___
Enhancement
___
- Add `name` field to GitHub GraphQL queries for users and team members
- Update version to 1.2.12-beta with changelog entry
___
```mermaid
flowchart LR
A["GraphQL Queries"] …
```

[Integration][Github] Include Name Key in GitHub User and Member Kind

---

integrations/checkmarx-one/.port/resources/blueprints.json
integrations/checkmarx-one/CHANGELOG.md
integrations/checkmarx-one/pyproject.toml

What -
Add Checkmarx icon name
Why -
The checkmarx logo is should appear in the checkmarx integration.
How -
Update the blueprint json icon
___
Enhancement
___
- Update blueprint icons from `AppRunner` to `Checkmarx`
- Apply consistent branding across all scan result blueprints
- Update changelog to reflect icon changes
___
```mermaid
flowchart LR
A["Blueprint Configuration"] --> B["Icon Update"]
B --> C["Checkmarx Branding"]
D["Changelog"] --> E["Version Documentation"]
```
<table><thead><tr><th></th><th …

[Integration] Update Checkmarx icons in blueprints.json to reflect correct branding

---

integrations/checkmarx-one/CHANGELOG.md
integrations/checkmarx-one/checkmarx_one/clients/client.py
integrations/checkmarx-one/pyproject.toml
integrations/checkmarx-one/tests/checkmarx_one/clients/test_base_client.py

What -
The `/api` is not properly handled.
Why -
The base url should only require base 
How -
fix the url base
___
Bug fix
___
- Fixed API URL construction in Checkmarx client
- Improved error handling in paginated requests
- Updated version to 0.1.4-dev
___
```mermaid
flowchart LR
A["Base URL"] --> B["URL Join Fix"]
B --> C["Correct API Endpoint"]
D["Paginated Request"] --> E["Better Error Handling"]
``` …

[Integration][Checkmarx] Fix bug with api url construction

---

integrations/jira/jira/overrides.py
integrations/jira/main.py

What - Add support for `expand` param to jiraIssue
Why - Feature is required to integrate extra content from JIRA like changelog or transitions. 
How - Handle `expand` param properly if present in the mappings configurations. Same way as when mapping projects.
Sample data container `changelog` section.

[Integration][JIRA] Add expand param support to jiraIssuse 

---

CHANGELOG.md
pyproject.toml

[Core] bumped core version

---

integrations/aws-v3/.port/spec.yaml
integrations/aws-v3/CHANGELOG.md
integrations/aws-v3/pyproject.toml

- **fix: add use_organizations to spec file**
- **chore: bump version and change log**
What - add missing env var in spec file
Why - forgot to add it to the spec file
How - add it to the spec file

[Integration][AWS-v3] add missing use organizations config

---

integrations/aws-v3/.port/spec.yaml
integrations/aws-v3/CHANGELOG.md
integrations/aws-v3/pyproject.toml

- **feat: rename aws-v3 integration to AWS Hosted by Port**
- **chore: update aws-v3 to version 1.0.1-beta with improvements**
What -
Why -
How -
___
Enhancement
___
- Rename aws-v3 integration to "AWS Hosted by Port"
- Update integration version to 1.0.1-beta
- Add disableDefaultInstallationMethods configuration option
___
```mermaid
flowchart LR
A["aws-v3 integration"] --> B["AWS Hosted by Port"]
B --> C["Version 1.0.1-beta"]
C --> D["Enhanced configuration"]
``` …

[Integration][AWS-v3] disable default installation schemas except hosted by port ocean 2

---

integrations/github/pyproject.toml

What - Bump GitHub Ocean Integration
Why - Pyproject file does not reflect version on changelog
How - Update pyproject file to match changelog
___
Bug fix
___
- Update GitHub Ocean integration version to 1.5.0-beta
- Fix version mismatch between pyproject.toml and changelog
___
```mermaid
flowchart LR
A["pyproject.toml"] -- "version bump" --> B["1.5.0-beta"]
```
<table><thead><tr><th></th><th align="left">Relevant …

[Integration][GitHub] Bump Github Ocean

---

CHANGELOG.md
pyproject.toml

What -
bump ocena core version to 0.28.3
Why -
How -
___
Bug fix
___
- Bump ocean core version to 0.28.3
- Fix issue with empty eventId being sent
___
```mermaid
flowchart LR
A["Version 0.28.2"] --> B["Version 0.28.3"]
B --> C["Fix empty eventId issue"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details> …

[Core] feat: bump version for ocean core

---

CHANGELOG.md
port_ocean/core/integrations/mixins/sync_raw.py
pyproject.toml

What - Use spawn for multiprocessing in windows machines
Why - `fork` startup method is not supported in windows
How - handle case we run on windows machine and switch to `spawn` startup method
___
Bug fix
___
- Fix multiprocessing startup method for Windows compatibility
- Switch from `fork` to `spawn` method on Windows platforms
- Add platform detection to handle OS-specific requirements
___
```mermaid
flowchart LR
A["Platform Detection"] --> B["Windows Check"]
B --> …
```

[Core] Use spawn for multiprocessing in windows machines

---

CHANGELOG.md
integrations/_infra/Dockerfile.Deb
pyproject.toml

Add write permissions for the ocean user  to /etc/ssl/certs
___
Bug fix
___
- Fix ocean user permissions for SSL certificate management
- Add recursive and default ACL permissions to `/etc/ssl/certs`
- Update version to 0.28.5 with changelog entry
___
```mermaid
flowchart LR
A["ocean user"] --> B["/etc/ssl/certs directory"]
B --> C["Recursive ACL permissions"]
B --> D["Default ACL permissions"]
C --> E["Read/Write/Execute access"]
D --> E
```
<details> <summary><h3> …

[Core] Add write permissions for the ocean user  to /etc/ssl/certs

---

integrations/checkmarx-one/CHANGELOG.md
integrations/checkmarx-one/integration.py
integrations/checkmarx-one/pyproject.toml

What -  Add ResourceConfig to List of Resources in Integration Config File
Why - Integration fails to start in fresh environment due to validation errors in CheckmarxOnePortAppConfig as it could not find the default ResourceConfig model.
How -
- Added ResourceConfig to List of Resources in Integration Config File
___
Bug fix
___
- Add `ResourceConfig` to integration resource types list
- Fix validation errors in fresh environment setup
- Update type annotations to …

[Integration][Checkmarx One] Add ResourceConfig to List of Resources in Integration Config File

---

integrations/azure-devops/CHANGELOG.md
integrations/azure-devops/azure_devops/client/azure_devops_client.py
integrations/azure-devops/azure_devops/misc.py
integrations/azure-devops/examples/example-blueprints.json
integrations/azure-devops/examples/example-mappings.yaml
integrations/azure-devops/main.py
integrations/azure-devops/pyproject.toml
integrations/azure-devops/tests/azure_devops/client/test_azure_devops_client.py

What - Added Support for Iteration kind to Azure DevOps
Why -
How -
___
Enhancement
___
- Added support for Iteration kind in Azure DevOps integration
- Implemented iteration classification logic (sprint, release, milestone, epic)
- Added recursive parsing for iteration hierarchies
- Included example mappings and resync functionality
___
```mermaid
flowchart LR
A["Azure DevOps API"] --> B["Iteration Client"]
B --> C["Classification Parser"]
C --> D["Iteration Types"]
D …
```

[Integration][Azure DevOps] Added support for Iteration kind in Azure DevOps

---

CHANGELOG.md
port_ocean/clients/port/mixins/integrations.py
pyproject.toml

What - added date as `extractionTimestamp` in the post to port
Why - to track how much time it takes to ingest the raw data
___
Enhancement
___
- Added extraction timestamp to raw data ingestion
- Includes current datetime in ISO format for tracking
___
```mermaid
flowchart LR
A["Raw Data"] --> B["Add Timestamp"] --> C["Post to Port API"]
```
<table><thead><tr><th></th><th align="left">Relevant …

[Core] added extractionTimestamp to post_integration_raw_data

---

integrations/aws-v3/.port/resources/port-app-config.yml
integrations/aws-v3/CHANGELOG.md
integrations/aws-v3/pyproject.toml

What - Fixed a bug in the AWS Organization Account kind where the title property was incorrectly set to use "AccountName" instead of the correct "Name" property.
Why -
How -

[Integration][AWS-V3] Fix Issue With AWS Organization Kind Title

---

integrations/azure-devops/.port/spec.yaml
integrations/azure-devops/CHANGELOG.md
integrations/azure-devops/pyproject.toml

What - Added installation docs params to Azure devOps spec file

[Integration][Azure DevOps] Added support in spec file for embed docs feature

---

integrations/gitlab-v2/gitlab/clients/auth_client.py
integrations/gitlab-v2/gitlab/clients/base_client.py
integrations/gitlab-v2/tests/clients/test_auth_client.py
integrations/gitlab-v2/tests/clients/test_base_client.py
integrations/gitlab-v2/tests/clients/test_refresh_token_integration.py

What -
Refresh token if it was expired during runtime in Oauth Sass.
Why -
Taking a value that is injected mid run to the container when token is invalidated.
How -
Read the token from a file that was defined in Ocean helm.

[Integration] [Gitlab] feat: refresh token on run

---

integrations/gitlab-v2/CHANGELOG.md
integrations/gitlab-v2/pyproject.toml

What -
Bump gitlab-v2 version
Why -
How -
___
Other
___
- Bump GitLab v2 integration version from 0.2.35 to 0.2.36
- Add changelog entry for refresh token mid-session improvement
___
```mermaid
flowchart LR
A["Version 0.2.35"] --> B["Version 0.2.36"]
B --> C["Refresh Token Mid-Session"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td>< …

[Integration][Gitlab] bump gitlab-v2 version

---

integrations/aws-v3/CHANGELOG.md
integrations/aws-v3/aws/auth/providers/assume_role_with_web_identity_provider.py
integrations/aws-v3/aws/auth/strategies/organizations_strategy.py
integrations/aws-v3/pyproject.toml
integrations/aws-v3/resync.py

Prevent single account failures from breaking multi-account resync and improve observability.
**Problem:** When `get_allowed_regions()` failed for any account (e.g., OIDC credential errors), the entire resync loop would break, preventing resource sync across all accounts.
**Impact:** One failing account caused complete resync failure for the entire organization.
**Resilience:**
- Added try-catch around `get_allowed_regions()` to skip failing accounts instead of breaking the loop
- Resync now continues with working accounts when some fail
**Observability:**
- Added role ARN to credential refresh errors for account identification
- Log each account being processed and region discovery results
- Log which accounts fail and why, with completion summary
**Example logs:**
Please leave one …

[Integration][AWS-v3] - Improve logging and resilience on region failure
