port-labs/ocean

changelog/PORT-4337.improvement.md, port_ocean/clients/port/authentication.py, port_ocean/clients/port/client.py, port_ocean/clients/port/mixins/blueprints.py, port_ocean/clients/port/mixins/entities.py, port_ocean/clients/port/mixins/integrations.py, port_ocean/clients/port/utils.py, port_ocean/core/handlers/entities_state_applier/port/applier.py, port_ocean/port_defaults.py
What - Some of the PortClient request errors dont show the error message
How - normalized the way to handle the http response
=> PORT-4337 Improved error PortClient handling

changelog/PORT-4341.bugfix.md, port_ocean/clients/port/mixins/integrations.py
What - The integration failed because there is no field config on the integration after the init
Why - When creating the integration it did not pass the config
How - Passed empty config on start
=> PORT-4341 fixed integration with empty config on start

changelog/PORT-4343.bugfix.md, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/.port/defaults/.gitignore, port_ocean/port_defaults.py
What - The initializePortResources failed if there is an unknown file in the  resources folder
Why - Ocean raise an error for unknown file types without checking if this file is known
How - Moved the check of the file name before the file type
=> PORT-4343 resolving error for unknown default file

integrations/gitlab/changelog/PORT-4380.improvement.md, port_ocean/cli/commands/new.py, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/pyproject.toml
What - The current scaffold ocean version is outdated
Why - The ocean version is a static string
How - Using the current ocean version
=> Using the current ocean version for ocean new deps

changelog/PORT-4398.bugfix.md, changelog/PORT-4411.bugfix.md, port_ocean/context/event.py, port_ocean/core/integrations/mixins/sync.py
What - Pass resource config inside the event context
Why - In case multiple resource kinds were specified inside the app config, the resync method couldn't know for which resource block ocean referred to, by passing the resource config inside the context, the integration gets the resource config that is relevant without the need for any extra logic 
How - Create event context per resource before running the resync method
=> Pass resource config inside the event context

changelog/bugfix.md, port_ocean/core/handlers/entities_state_applier/port/order_by_entities_dependencies.py, port_ocean/core/models.py, pyproject.toml
What - If the identifier was not found in the jq it would set a "None" as the identifier which is invalid because we dont want to create the wrong entity
Why - The fields went through a parsing that made them string if they are not
How - Changed the typing and remove the parsing
=> Fix entity jq parsing

changelog/improvement.md, port_ocean/clients/port/authentication.py, port_ocean/clients/port/client.py, port_ocean/clients/port/mixins/blueprints.py, port_ocean/clients/port/mixins/entities.py, port_ocean/clients/port/mixins/integrations.py, port_ocean/clients/utils.py
What - Each integration needs to handle its own ccontext of httpx async client
Why - If there are  multiple threads (like with the kafka event listener) the httpx async client can raise error because you cannot use httpx async client from another thread
How - In ocean there is a client stored in a local proxy like the ocean & event contexts so i moved it to a more reasonable place so integrations will use it instead of handling it on their own
=> moved the http client to more accessible for integrations

CHANGELOG.md, changelog/1.bugfix.md, port_ocean/config/base.py, pyproject.toml
What - Ocean made integration config of type object camelized
Why - the parsing iterates recursively over projects
How - If the value type in the settings is a meta class recursing else the value should not be camelized
=> Fix config yaml parsing

integrations/gitlab/.port/spec.yaml, integrations/gitlab/CHANGELOG.md, integrations/gitlab/config.yaml, integrations/gitlab/gitlab_integration/bootstrap.py, integrations/gitlab/gitlab_integration/ocean.py, integrations/gitlab/pyproject.toml, integrations/jira/Makefile, integrations/newrelic/Makefile, integrations/pagerduty/Makefile
What - the app host is failing the integration to start if not set
Why - the property is required and sometimes the gitlab does not have a webhook for the groups in gitlab
How - made it so the feature is optional
=> optional webhook

changelog/2.bugfix.md, changelog/3.bugfix.md, port_ocean/core/event_listener/kafka/event_listener.py
What - Handle where the integration receive an event of deletion from the port's Kafka
Why -
How - Check whether there is after
=> Handle delete events from change log where there is no after

integrations/gitlab/.port/resources/blueprints.json, integrations/gitlab/.port/resources/port-app-config.yaml, integrations/gitlab/CHANGELOG.md, integrations/gitlab/changelog/PORT-4555.improvement.md, integrations/gitlab/pyproject.toml
What - Change the default blueprint terminology
=> Port 4555 change the name microservice to repository in all the git templates

changelog/PORT-4483.improvement.md, port_ocean/core/handlers/port_app_config/api.py, port_ocean/core/handlers/port_app_config/base.py
What - Ocean error message for empty port app config is not enough and we want to enrich it with more readable text
Why - When using the integration with no port app config ocean simply raise pydantic error
How - logged before raising the error stating there is an issue with the mapping and  logging when the port app config is empty
=> PORT-4483 logging for empty configuration

integrations/gitlab/CHANGELOG.md, integrations/gitlab/changelog/1.bugfix.md, integrations/gitlab/gitlab_integration/gitlab_service.py, integrations/gitlab/pyproject.toml
What - Gitlab integration was failing on push live events
Why - The code tried to fetch from the cache but got key error
How - used .get instead of [] to get none when no cache found and then fill the cache with information
=> Fix gitlab project key error

integrations/gitlab/CHANGELOG.md, integrations/gitlab/changelog/1.bugfix.md, integrations/gitlab/changelog/1.improvement.md, port_ocean/context/event.py
Gitlab changelogs & bug with the event handling in ocean (using the wrong key)
=> Port 4619 cancel resync event before starting a new one

integrations/sonarqube/CHANGELOG.md, integrations/sonarqube/client.py, integrations/sonarqube/pyproject.toml
What - Sonarqube didnt log for http error when paginating requests
Why - used print instead of the logger
How - changed to print
=> Changed print in the http error handling to log info

integrations/pagerduty/.port/resources/port-app-config.yaml, integrations/pagerduty/CHANGELOG.md, integrations/pagerduty/changelog/PORT-4964.bugfix.md, integrations/pagerduty/pyproject.toml
What - The pagerduty integration wont return the oncall for the defaullt resourcees
Why - wrong key for the on call (.oncall_user instead of .__oncall_user)
How - Updated default resources
=> Port 4964 fix pagerduty default mapping

integrations/pagerduty/CHANGELOG.md, integrations/pagerduty/changelog/PORT-4965.feature.md, integrations/pagerduty/clients/pagerduty.py, integrations/pagerduty/integration.py, integrations/pagerduty/main.py, integrations/pagerduty/pyproject.toml
What - Clients are having errors because we query alot of objects
Why - API limitations
How - Allowed the user to pass query params for the api calls using the port app config
=> Port 4965 extend pagerduty query capabilities

integrations/gitlab/.port/resources/port-app-config.yaml, integrations/gitlab/CHANGELOG.md, integrations/gitlab/changelog/PORT-5028.bugfix.md, integrations/gitlab/gitlab_integration/gitlab_service.py, integrations/gitlab/pyproject.toml
What - The integration raised an error when fetching a single project
Why - Wrong usage of the function that checks if the project should be included by the filter. `project.path_with_namespace` instead of just `project` was passed to the function
How - removed the `path_with_namespace`
```python
future: <_GatheringFuture finished exception=AttributeError("'str' object has no attribute 'path_with_namespace'")>
Traceback (most recent call last):
File "/app/gitlab_integration/events/hooks/base.py", line 34, in on_hook
project = self.gitlab_service.get_project(project_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/app/gitlab_integration/gitlab_service.py", line 192, in get_project
if self.should_run_for_project(project.path_with_namespace): …
```
=> PORT-5028 Fixed project fetching bug

CHANGELOG.md, port_ocean/cli/commands/sail.py, port_ocean/config/settings.py, port_ocean/core/event_listener/once.py, port_ocean/run.py, port_ocean/utils.py, pyproject.toml
What -
- Fixed the `initialize-port-resources` option in `ocean sail` to not be a flag.
- Changed default of `initialize-port-resources` to `true`.
- Catch all exceptions in the resync of ONCE event listener,to make sure the application will exit gracefully.
Why -
How -
=> Fix `initlialize-port-resources` flag and change default to `True` and catch failures in ONCE resync

CHANGELOG.md, port_ocean/consumers/kafka_consumer.py, port_ocean/context/utils.py, port_ocean/core/event_listener/kafka.py, pyproject.toml
What -  Fixed the following error, which was caused as a result of the code running the resync in a synchronous way which caused the integration to no poll message from kafka in the max timeout period.
```
ERROR    | KafkaError{code=_ASSIGNMENT_LOST,val=-142,str="Commit failed: Local: Group partition assignment lost"}
ERROR    | KafkaError{code=_MAX_POLL_EXCEEDED,val=-147,str="Application maximum poll interval (300000ms) exceeded by 193ms"}
```
Why -
How - Fixed by spawning the resync in a separate thread, which allowed the code to keep polling messages from kafka. This also takes advantage of the `ABORT` mechanism that we previously implemented that once new resync arrives it closes the current running resync. 
```
2023-11-09 16:52:52.860 | WARNING  | ABORTING RESYNC EVENT DUE TO NEWER …
```
=> [Ocean] Fix Kafka poll max timeout

CHANGELOG.md, port_ocean/clients/port/authentication.py, port_ocean/clients/port/client.py, port_ocean/clients/port/mixins/blueprints.py, port_ocean/clients/port/mixins/entities.py, port_ocean/clients/port/mixins/integrations.py, port_ocean/clients/port/utils.py, port_ocean/helpers/retry.py, port_ocean/utils.py
- Add retry decorator on 401 for requests against Port ( reason we don't use the HTTPX Retry Class in this case is because we need to re-run the `token` property that re-initializes the token )
- Add HTTPX retry client, both for port client as well as for integrations to use to handle different http errors, for better durability  - #224  uses implementation from - https://github.com/encode/httpx/issues/108#issuecomment-1434439481
- Fix `repeat_every` to calculate failed as repetition runs as well ( For Once Event Listener )
=> [Ocean] Add helper for integrations to handle failures with Third Party APIs & Fix 401 against Port API when token expired

.github/workflows/release-integrations.yml
What - The CD for integration fails after changing the flow
Why - Failure when handling exit code for docker inspect command
How - better handling
=> Port 5610 fix ci failing for non existing image

CHANGELOG.md, Makefile, changelog/PORT-5453.improvement.md, changelog/PORT-5711.improvement.md, docs/framework-guides/docs/develop-an-integration/publish-an-integration.md, integrations/argocd/Makefile, integrations/azure/Makefile, integrations/firehydrant/Makefile, integrations/gitlab/Makefile, integrations/jira/Makefile, integrations/kafka/Makefile, integrations/kubecost/Makefile, integrations/newrelic/Makefile, integrations/opencost/Makefile, integrations/opsgenie/Makefile, integrations/pagerduty/Makefile, integrations/sentry/Makefile, integrations/servicenow/Makefile, integrations/snyk/Makefile, integrations/sonarqube/Makefile, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/Makefile, pyproject.toml
What - Swapped `poetry lock --check` with `poetry check --lock`
Why - `poetry lock --check` is deprecated
=> PORT-5711-replace-poetry-lock-check-with-the-new-poetry-check-lock

.github/workflows/validate-integration-files.yml, integrations/argocd/pyproject.toml
What - Ocean version validation wont work for forked projects
Why - there is a diff check between current branch to origin main and the fork branch might be also main
How - adding a remote to the public repo to check against it instead
=> checking fork

CHANGELOG.md, port_ocean/clients/port/mixins/entities.py, port_ocean/clients/port/utils.py, port_ocean/core/defaults/initialize.py, port_ocean/core/handlers/port_app_config/models.py, pyproject.toml
What - 
- Added handling for aggregation properties when initializing the integration, so it will patch the aggregation properties after creating the relations (PORT-5717)
- Changed entity property in the `portResourceConfig` to be required instead of optional, as we don't support creation of blueprints as part of the app config (PORT-4549) 
- Fixed port merge cr comments in #279  
Why -
- It was failing to create blueprints with aggregation properties due to the order in which we create the blueprints
- There is no need for it any more, and it was causing integration to use `# type ignore` as it was relying on the entity to exist in the port app config
How -
- added the aggregation properties to be patched after relations are being created
- removed optional
Please leave one option from …
=> Support creation of blueprints with aggregation properties & Change entity from optional to required in port app config

.github/workflows/apply-release.yml, .github/workflows/release-integrations.yml
What - update repository workflows to use actions/checkout@v4 instead of v2
Why - because v2 is old and deprecated
How - drop-in replacement
=> PORT-5775 Update workflows to use checkout v4

integrations/azure/.port/resources/blueprints.json, integrations/azure/CHANGELOG.md, integrations/azure/pyproject.toml, integrations/gitlab/.port/resources/blueprints.json, integrations/gitlab/CHANGELOG.md, integrations/gitlab/pyproject.toml, integrations/jira/.port/resources/blueprints.json, integrations/jira/CHANGELOG.md, integrations/jira/pyproject.toml, integrations/kafka/.port/resources/blueprints.json, integrations/kafka/CHANGELOG.md, integrations/kafka/pyproject.toml, integrations/sentry/.port/resources/blueprints.json, integrations/sentry/CHANGELOG.md, integrations/sentry/pyproject.toml
What - update some stale blueprint identifiers in relations
Why - they weren't updated last time
How - update
=> PORT-5799 fix stale blueprint identifiers in ocean gitlab

integrations/terraform-cloud/.port/spec.yaml, integrations/terraform-cloud/changelog/PORT-5806.improvement.md, integrations/terraform-cloud/client.py, integrations/terraform-cloud/main.py, integrations/terraform-cloud/pyproject.toml
Removing redundant configuration from the terraform cloud integration
=> Port 5806 remove terraform cloud host from tf cloud integration

integrations/terraform-cloud/.port/spec.yaml, integrations/terraform-cloud/CHANGELOG.md, integrations/terraform-cloud/changelog/PORT-5858.feature.md, integrations/terraform-cloud/client.py, integrations/terraform-cloud/main.py
What - Adding the option to pass terraform cloud host
Why - We removed it on the previous version and it is now required
How - Applied the previous code
=> Port 5858 allow passing terraform cloud host

CHANGELOG.md, port_ocean/clients/port/mixins/blueprints.py, port_ocean/core/defaults/common.py, port_ocean/core/defaults/initialize.py, port_ocean/core/handlers/entities_state_applier/port/applier.py, port_ocean/core/integrations/mixins/sync_raw.py, port_ocean/exceptions/port_defaults.py, pyproject.toml
What - 
- Add support to create pages
- Add blueprints and integration validation existence before defaults creation
- Add more verbosity on the delete entities resync process
Why -
- To be able to create pages
- To reduce the noisiness  when restarting the integration in the audit log
- To help with understanding the progress in entities deletion
=> [Core] Add support to create pages as part of integration setup

CHANGELOG.md, changelog/PORT-5938.bugfix.md, port_ocean/core/handlers/port_app_config/models.py, pyproject.toml
What - Integrations failed to map team property
Why - the team property was missing in the port app config model
=> Port 5938 ocean integration mapping to team property is missing

CHANGELOG.md, port_ocean/config/settings.py, port_ocean/utils.py, pyproject.toml
What - Increased default timeout to 30 seconds, and made it configurable
Why - To reduce the amount of failures against third party integrations if it takes them longer than the 5 seconds to return a response.
How - Increased to 30 and added it to the global configuration.
=> [Core] Increase default timeout to the re-usable async client

.github/workflows/release-integrations.yml
Reverts port-labs/ocean#266
Due to failures in build - https://github.com/port-labs/ocean/actions/runs/7541969887/job/20529790194 
We will add it in a future PR with `Docker build and Push` action
=> Revert "Multi Platform Docker Builds"

.github/ISSUE_TEMPLATE/integration-enhancement.yml, .github/ISSUE_TEMPLATE/ocean-framework-enhancement.yml
What - Changed the framework issue template to include framework related template, and same for integration issue tempate
Why - It had the opposite templates
How -
=> [Ocean] Fix templates to point to the correct type

CHANGELOG.md, changelog/PORT-6836.bugfix.md, port_ocean/log/sensetive.py, pyproject.toml
What - Integrations were failing with regex error over the sensitive fields
Why - We are compiling the sensitive values to redact later from the logs and we didnt use escaping over those values
How - Used re.escape()
=> (Bugfix) - Integrations crashing with regex error after 0.5.0

integrations/jenkins/README.md, integrations/jira/README.md
What - fix broken links to Port's documentation for some of the integrations
Why - because the docs tree in Port's docs changed
How - update to the correct links
=> PORT-6853 Update broken links in READMEs

CHANGELOG.md, port_ocean/utils/cache.py, pyproject.toml
What - Changing ocean to cache functions by name, args and kwargs 
Why - Ocean calls cache for differently parameterized functions
How - Adding caching by hash of args and kwargs, removing param
=> Changed caching to be with params

CHANGELOG.md, changelog/PORT-7262.feature.md, docs/framework-guides/docs/develop-an-integration/integration-spec-and-default-resources.md, port_ocean/config/dynamic.py, pyproject.toml
What - added array to config.types
Why - to support more types for config variables
How - added a new case in the switch case in dynamic.py
=> PORT-7262-add-a-config-type-for-array-in-ocean

integrations/argocd/.port/spec.yaml, integrations/argocd/CHANGELOG.md, integrations/argocd/client.py, integrations/argocd/main.py, integrations/argocd/pyproject.toml
What - Added support for `managed-resource `by ArgoCD application
Why - We are working on a new mini guide that helps users to connect Argocd to it's deployed image. To be able to achieve this, we needed a way to get all deployments created by an Argo application since each deployment contains the running image. 
How - Used the ArgoCD managed resource API https://host/applications/{app_name}/managed-resources
https://cd.apps.argoproj.io/swagger-ui#operation/ApplicationService_ManagedResources
=> [Integration][Argocd] - Add support for managed resources

CHANGELOG.md, changelog/Items-to-parse.feature, docs/framework-guides/docs/framework/features/resource-mapping.md, port_ocean/core/handlers/entity_processor/jq_entity_processor.py, port_ocean/core/handlers/port_app_config/models.py, pyproject.toml
What - 
A valid mapping can be looked as follows:
```yaml
- kind: issue
selector:
query: .item.name != 'test-item' and .issueType == 'Bug' 
port:
itemsToParse: .fields.components
entity:
mappings:
identifier: .item.name
title: .item.name
blueprint: '"testBlueprint"'
properties: {}
relations:
issue: .key
```
issue's json from api:
```json
{
"url": "https://example.com/issue/1",
"status": "Open",
"issueType": "Bug",
"components": [{"name": "Authentication"}, {"name": "Frontend"}],
"assignee": "user1",
"reporter": "user2",
"creator": "user3",
"priority": "High",
"created": "2024-03-18T10:00:00Z",
"updated": "2024-03-18T12:30:00Z",
"key": "ISSUE-1",
}
```
it will map the component attribute array of each issue got from the api to "testBlueprint" entity, with identifier and parser equals to …
=> [Framework] Added support for items to parse in mapping

integrations/gitlab/CHANGELOG.md, integrations/gitlab/gitlab_integration/ocean.py, integrations/gitlab/pyproject.toml
What - bugfix - could not run on startup when not configuring param tokenGroupsHooksOverridMapping
Why - integration was failing to startup after merge
How - added check for not none on the param before using it
=> PORT-7326-gitlab-0-1-58-bugfix-gitlab

integrations/gitlab/CHANGELOG.md, integrations/gitlab/changelog/PORT-7141.feature.md, integrations/gitlab/gitlab_integration/events/hooks/push.py, integrations/gitlab/gitlab_integration/git_integration.py, integrations/gitlab/pyproject.toml
What - listening to default branch on changes, unless mentioned a specific branch in the mapping
Why - for a more correct way to ingest projects to port
How - added None to branch in config as default, then on push hook checked if None, then used project's default branch.
=> [Integrations][Gitlab] Listen to default branch of repository by default

CHANGELOG.md, port_ocean/log/logger_setup.py, pyproject.toml
What - Added a handler for a bug in loguru which fails to deserialize an error 
Why -
How -
=> [Core] Fix the logger to handle exception deserializer

.github/workflows/release-framework.yml
What -
Why - CI failed on error 
```
[Invalid workflow file: .github/workflows/release-framework.yml#L35](https://github.com/port-labs/ocean/actions/runs/8455594726/workflow)
The workflow is not valid. .github/workflows/release-framework.yml (Line: 35, Col: 14): Unexpected symbol: 'ref_name:1'. Located at position 8 within expression: github.ref_name:1
```
How -
=> [CI] Fix release framework workflow to extract the version correctly 

integrations/launchdarkly/.port/resources/port-app-config.yaml, integrations/launchdarkly/.port/spec.yaml, integrations/launchdarkly/CHANGELOG.md, integrations/launchdarkly/config.yaml, integrations/launchdarkly/pyproject.toml
What 
- Updated Launchdarkly Documentation Path in spec.yaml
- Resolved an [issue](https://github.com/port-labs/ocean/issues/487) where the relationship between feature flags and environments was causing synchronization of feature flags to fail. ()
Why - Feature Flags were failing to sync as a result.
=> [Integration][Launchdarkly] - Fixed Issue Causing Feature Flags sync to fail

.github/workflows/release-integrations.yml
What - Release integration would update the spec for integration dev version
Why - missing if in the workflow
How - Added a check that should skip the spec publish for integration dev version
=> skipping spec publish for dev versions

integrations/pagerduty/.port/resources/blueprints.json, integrations/pagerduty/.port/resources/port-app-config.yaml, integrations/pagerduty/CHANGELOG.md, integrations/pagerduty/changelog/0.1.52.improvement.md, integrations/pagerduty/pyproject.toml
What - Users reported that the oncall property in their PagerDuty service blueprint contains array of users, while in fact, it should just be one user
Why - Their PagerDuty service dashboard also correctly lists only one user as oncall
How - After investigation, it was understood that an escalation policy can have many levels. On the PagerDuty dashboard, the user in the escalation policy with level 1 get's assigned as the primary oncall user. Here is the current service discovery dashboard in our PD account:
PD Service in Port
[Who is on call](https://developer.pagerduty.com/api-reference/3a6b910f11050-list-all-of-the-on-calls)
=> [Integration][PagerDuty] - Map oncall user with highest escalation level

integrations/argocd/.port/resources/port-app-config.yaml, integrations/argocd/CHANGELOG.md, integrations/argocd/changelog/0.1.40.bugfix.md, integrations/argocd/client.py, integrations/argocd/pyproject.toml
What - A PR to fix the issue reported [here](https://github.com/port-labs/ocean/issues/577) when trying to get item manage resources items 
Why -
How - it is understood that some apps may not be managing any k8s resources. This causes the ArgoCD to return null, or without the items keyword. So instead of using a square bracket to fetch the response, we now use .get("items", [])
=> [Integration][ArgoCD] - Fix managed resources KeyError

CHANGELOG.md, port_ocean/context/event.py, pyproject.toml
What - Allowing parent event context override
Why - To allow using another event context attributes within task sub threads 
=> [Framework] Allowing parent event context override

integrations/sonarqube/CHANGELOG.md, integrations/sonarqube/client.py, integrations/sonarqube/pyproject.toml
What - The sanity check failed
```
By: Port.io
Setting sail... ⛵️⚓️⛵️⚓️ All hands on deck! ⚓️
🌊 Ocean version: 0.5.17
🚢 Integration version: 0.1.46
2024-05-01 12:51:20.168 | INFO     | Registering resync event listener for kind projects
2024-05-01 12:51:20.169 | INFO     | Registering resync event listener for kind issues
2024-05-01 12:51:20.169 | INFO     | Registering resync event listener for kind saas_analysis
2024-05-01 12:51:20.170 | INFO     | Registering resync event listener for kind analysis
2024-05-01 12:51:20.171 | INFO     | Registering resync event listener for kind onprem_analysis
2024-05-01 12:51:20.180 | INFO     | Found default resources, starting creation process
2024-05-01 12:51:20.180 | INFO     | Fetching integration with id: my-sonarqube-integration
2024-05-01 …
```
=> fixed sanity check with non json response

integrations/gitlab/CHANGELOG.md, integrations/gitlab/gitlab_integration/ocean.py, integrations/gitlab/pyproject.toml
What - Add logs and return the error when cannot process event on Gitlab
Why - app crashes when cannot parse JSON requests
How - Add try-catch blocks
=> [Integration][Gitlab] add missing try catch blocks

integrations/azure-devops/.port/resources/port-app-config.yaml, integrations/azure-devops/CHANGELOG.md, integrations/azure-devops/pyproject.toml
What - Fixed issue of the azure devops's service routing
Why - It sent the users to the api and not the actual repository
How - Switched from url to remoteurl
https://docs.getport.io/build-your-software-catalog/sync-data-to-catalog/git/azure-devops/
=> [Integrations] [Azure Devops] Fixed remote url error

integrations/kubecost/.port/resources/port-app-config.yaml, integrations/kubecost/CHANGELOG.md, integrations/kubecost/changelog/0.1.39.bugfix.md, integrations/kubecost/client.py, integrations/kubecost/main.py, integrations/kubecost/pyproject.toml
What - The `cloud` kind of the KubeCost exporter was throwing 404 error because KubeCost had change their API route. This led to the exporter hanging up during the resync process. There was also an issue with the mapping of resource so I adjusted the mapping to map all resources as there may be several cost estimates for the same cloud service.
Why -
How - Updated the URL of the cloud cost to use the correct path
[Deprecated Cloud Cost API in KubeCost version 1.X](https://docs.kubecost.com/v/1.0x/apis/apis-overview/cloud-cost-api#cloud-cost-aggregate-api)
[Current Cloud Cost API in KubeCost version 2.2](https://docs.kubecost.com/apis/monitoring-apis/cloud-cost-api)
=> [integration][KubeCost] - Fix Kubecost 404 error

integrations/azure-devops/.port/resources/port-app-config.yaml, integrations/azure-devops/CHANGELOG.md, integrations/azure-devops/pyproject.toml
What - Fix default relation mapping from service to project
Why - due to using `gsub(" ", "")` to remove empty spaces
How -
=> [Integration][ADO] Fix default relation mapping from service to project

changelog/1.bugfix.md, changelog/1.improvement.md, changelog/2.bugfix.md, port_ocean/core/event_listener/base.py, port_ocean/core/event_listener/polling.py, port_ocean/ocean.py, port_ocean/utils/signal.py
What - After shutting down an integration it will keep running
Why - Incorrect handling of async tasks
How - Better handling and moved from listenning to signal to the fastapi lifespan feature
=> fix(Port 8334): ocean integration wont shut down without forcing it

integrations/_infra/Dockerfile
What - Update the base image we use to build integration container images
Why - Because we're currently using `slim-buster` which is no longer maintained
How - Update to `slim-bookworm` which is the current stable LTS Debian distro
=> PORT-8407 Update container base image from slim-buster to slim-bookworm

CHANGELOG.md, changelog/1.bugfix.md, port_ocean/core/utils.py, pyproject.toml
What - gather_and_split_errors_from_results would handle baseexception errors incorrectly 
Why - wrong inheritance check
How - Updated the logic
=> Fix gather exception handling

CHANGELOG.md, port_ocean/config/settings.py, pyproject.toml
What - Without setting an identifier the integration failed
Why - incorrect pydantic validation over the integration settings
=> Fixed incorrect pydantic validation over the integration settings

integrations/aws/CHANGELOG.md, integrations/aws/integration.py, integrations/aws/poetry.lock, integrations/aws/pyproject.toml, integrations/aws/utils/overrides.py, integrations/aws/utils/resources.py
- **feat: add describe_resources config**
- **feat: add describe each to cloudcontrol**
- **fix: remove unnecessary describe_resources  in custom kinds**
What - Add describe_resources propery to AWS mapping.
Why - Most of CloudControl resources return without most of their properties like "Tags" propery is missing.
How - Add option on the config to describe each resource so all of their resources will return.
https://docs.aws.amazon.com/cloudcontrolapi/latest/userguide/resource-operations-list.html
=> PORT 8673 aws integration add describe resources to config

integrations/aws/CHANGELOG.md, integrations/aws/aws/session_manager.py, integrations/aws/pyproject.toml
- **fix: _aws_credentials overflow**
- **feat: bump version**
What - Fix array of credentials overflow
Why - each time the `reset` function runs the credentials array just appends the new credentials to the existing array
How - reset the array on each `reset` function run
=> [AWS Integration] aws credentials overflow

CHANGELOG.md, port_ocean/core/defaults/initialize.py, pyproject.toml
What - changelogDestination key may not exist
How - solved by safely get changelogDestination key instead of accessing it directly
=> [Framework] Safely get changelogDestination key instead of accessing it directly

integrations/aws/.port/spec.yaml, integrations/aws/CHANGELOG.md, integrations/aws/pyproject.toml, integrations/gcp/.port/spec.yaml, integrations/gcp/CHANGELOG.md, integrations/gcp/main.py, integrations/gcp/pyproject.toml
What - Added Deployment Requirements for AWS and GCP integrations
Why - To enable different deployment methods for both
How - Using new deployment method requirements feature in the frontend
=> [PORT-8788] [AWS] [GCP]  add requirements for deployment methods

integrations/aws/CHANGELOG.md, integrations/aws/aws/aws_credentials.py, integrations/aws/pyproject.toml, integrations/aws/utils/aws.py
What - Ensure that there's a default region for global AWS resources
Why - Creating an instance of the cloudcontrol client would fail if no AWS default region was known
How - Lookup default regions from the credentials
=> [PORT-8828] [AWS] Ensure default region for global resources

integrations/pagerduty/.port/resources/blueprints.json, integrations/pagerduty/.port/resources/port-app-config.yaml, integrations/pagerduty/.port/spec.yaml, integrations/pagerduty/CHANGELOG.md, integrations/pagerduty/changelog/0.1.75.improvement.md, integrations/pagerduty/integration.py, integrations/pagerduty/main.py, integrations/pagerduty/pyproject.toml
What - Added support Pagerduty escalation policy
Why -
How -
[Escalation Policy](https://developer.pagerduty.com/api-reference/51b21014a4f5a-list-escalation-policies)
=> [Integration][PagerDuty] -  Add support for escalation policy

CHANGELOG.md, port_ocean/config/settings.py, port_ocean/core/handlers/entity_processor/jq_entity_processor.py, port_ocean/core/handlers/port_app_config/base.py, pyproject.toml
What - Added a new ocean configuration option- Allow Environment variables jq access, which is true by default
Why - To have an option to hide sensitive information from the integration runner
How - Added Integration configuration
=> [Core] Added environment variables access restriction option

CHANGELOG.md, port_ocean/core/defaults/initialize.py, pyproject.toml
What - Fix handling of non existing config key in port app config
Why - When installing in Saas the config is not set yet and therefor we don't want to fail on that.
How -
=> [Framework] Fix handling of non existing config key in port app config

integrations/aws/.port/resources/port-app-config.yml, integrations/aws/CHANGELOG.md, integrations/aws/pyproject.toml
What - change the "get extra data" parameter to the correct name (matches the docs)
Why - the prev parameter is not the correct parameter
How - change the name to `useGetResourceAPI` 
=> [Integration][AWS] Fix wrong parameter name in default mapping

integrations/azure-devops/.port/spec.yaml, integrations/azure-devops/CHANGELOG.md, integrations/azure-devops/main.py, integrations/azure-devops/poetry.lock, integrations/azure-devops/pyproject.toml
Fixed [a bug in the Azure DevOps (ADO) integration](https://port-community.slack.com/archives/C05LZB72NM8/p1718010461875529) where project-scoped webhooks were not being created if the isProjectsLimited parameter was not explicitly set. The default value for this parameter is now set to True, ensuring that webhooks are created with the correct scope.
=> [Integration][ADO] Set the `isProjectsLimited` paramater to True by default

integrations/pagerduty/.port/resources/blueprints.json, integrations/pagerduty/.port/resources/port-app-config.yaml, integrations/pagerduty/.port/spec.yaml, integrations/pagerduty/CHANGELOG.md, integrations/pagerduty/changelog/0.1.79.improvement.md, integrations/pagerduty/clients/pagerduty.py, integrations/pagerduty/integration.py, integrations/pagerduty/main.py, integrations/pagerduty/pyproject.toml
What - Added the primary oncall user to the escalation policy blueprint
Why - Customers needed to know who is the current oncall for a given escalation policy
How - Used integration filters to allow users to bring oncall data as part of the resync event for the escalation_policy kind
=> [Integration][PagerDuty] - Add Oncall to Escalation policy

integrations/linear/.port/spec.yaml, integrations/linear/CHANGELOG.md, integrations/linear/pyproject.toml, integrations/statuspage/.port/spec.yaml, integrations/statuspage/CHANGELOG.md, integrations/statuspage/pyproject.toml, integrations/wiz/.port/spec.yaml, integrations/wiz/CHANGELOG.md, integrations/wiz/pyproject.toml
=> [Integrations][Wiz][Linear][Statuspage] Update links in Ocean description

integrations/sentry/CHANGELOG.md, integrations/sentry/clients/sentry.py, integrations/sentry/pyproject.toml
What - Added catching of missing headers in requests to the Sentry API
Why - Some requests seem not to have the header requested to make ratelimiting optimizations
How - Added try and catch in the request method
=> [Sentry] Added catch to ratelimiting header missing error

integrations/aws/CHANGELOG.md, integrations/aws/aws/session_manager.py, integrations/aws/main.py, integrations/aws/pyproject.toml, integrations/aws/utils/misc.py, integrations/aws/utils/resources.py
- **feat: add access denied handler to STS:AssumeRole**
- **feat: add access denied handler to custom kind resync**
- **feat: brute force global resource if does not have permissions in default region**
What - Read all regions in global resource
Why - Whenever there are no permissions in a region global resources (such as AWS::S3::Bucket) that only use the first default region cannot read any resources.
How - Read all regions until there's resources in any region
=> [Integration][AWS] fix: Cannot read global resources without regional permissions

integrations/servicenow/CHANGELOG.md, integrations/servicenow/changelog/0.1.47.improvement.md, integrations/servicenow/client.py, integrations/servicenow/pyproject.toml
What - Updated the Servicenow connectivity test to use an existing table (incident) rather than the instance table, which may require the user to grant extra permission
Why - As part of the connectivity check, we query the tapi/now/table/instance endpoint to retrieve information about the instance. One customer was particularly worried that they don't want the integration to access this table since it involve granting admin privileges. So, instead of querying another table, we use one of the existing tables which we have access to(incident) to perform the connectivity check. For us to know that the connection was successful, we display a sample incident to the console
How -
Include screenshots from your environment showing …
=> [Integration][Servicenow] - Update Connectivity Test

CHANGELOG.md, port_ocean/core/handlers/port_app_config/base.py, pyproject.toml
=> [Framework] Initialize missing _port_app_config

integrations/azure-devops/CHANGELOG.md, integrations/azure-devops/azure_devops/webhooks/webhook_event.py, integrations/azure-devops/pyproject.toml
What - Fixed webhook creation bug where each restart would create all webhooks again
Why - Bug
How - Webhook comparing publisherInputs would always fail because ADO pushes additional input
=> [AzureDevops] Added check only for project id when comparing publisher inputs

deployment/terraform/aws/ecs/modules/ecs_service/main.tf
What - #830 
Why - we were concatenating the type of the resource to the resource name causing it to exceed the allowed length of the resource 
How - remove the prefix for those resources
=> [Core][Deployment][ECS] - Fix resource name limit by 64

CHANGELOG.md, port_ocean/log/logger_setup.py, port_ocean/ocean.py, port_ocean/run.py, pyproject.toml
What - Flush logs on signal interrupt
Why - Logs that left in the buffer are not being send when application exits
=> Flush logs on signal interrupt

integrations/azure/.port/spec.yaml, integrations/azure/CHANGELOG.md, integrations/azure/pyproject.toml
Update the description content and the attribute target="_blank" to all tags such that the final becomes . Doing this will point the url to open a new browser tab instead of the current browser.
=> [Integration][Azure] Add _target='blank' attribute to spec links

integrations/wiz/.port/spec.yaml, integrations/wiz/CHANGELOG.md, integrations/wiz/pyproject.toml
Update the description content and the attribute target="_blank" to all tags such that the final becomes . Doing this will point the url to open a new browser tab instead of the current browser.
=> [Integration][Wiz] Added _target='blank' attribute to spec links

integrations/datadog/.port/spec.yaml, integrations/datadog/CHANGELOG.md, integrations/datadog/pyproject.toml
Update the description content and the attribute target="_blank" to all <a> tags such that the final becomes <a href=”some_link” target=”_blank”></a>. Doing this will point the url to open a new browser tab instead of the current browser.
=> [Integration][Datadog] Add _target='blank' attribute to spec links

integrations/aws/CHANGELOG.md, integrations/aws/aws/aws_credentials.py, integrations/aws/main.py, integrations/aws/pyproject.toml, integrations/aws/utils/aws.py, integrations/aws/utils/resources.py
What - 
Fixed an issue in the AWS integration where S3 buckets were not synced for all accounts.
Why - 
S3 buckets are a global resource type, meaning we only search for the first region showing these buckets and then stop searching to avoid rate limiting with AWS and wasting time. This caused users with multi-account setups to only list their first account's buckets.
How - 
Added an iteration of accounts on top of the existing process to ensure that S3 buckets are synced across all accounts.
=> [AWS] Bug fix global resources not synced for all accounts

integrations/aws/CHANGELOG.md, integrations/aws/main.py, integrations/aws/pyproject.toml, integrations/aws/utils/misc.py
What - We have implemented blacklist error handling for AWS errors in our system. This ensures that certain AWS error types are specifically caught and handled differently from other errors.
Why - Each AWS resource handles "not found" errors differently, making it challenging to distinguish between a resource not being found and an actual error in the system. This inconsistency can lead to misinterpretation of errors and inappropriate error handling. By adding blacklist error handling, we can provide more accurate and consistent error handling across different AWS resources.
How - We have introduced a blacklist mechanism that explicitly catches specific AWS error codes related to "not found" scenarios. These error codes are then handled separately from other types of errors, allowing us …
=> [Integration][AWS] throw error if no permissions on region

CHANGELOG.md, poetry.lock, port_ocean/clients/port/mixins/entities.py, port_ocean/core/handlers/entities_state_applier/base.py, port_ocean/core/handlers/entities_state_applier/port/applier.py, port_ocean/core/integrations/mixins/sync.py, port_ocean/core/integrations/mixins/sync_raw.py, pyproject.toml
What - Fixed resync issue when calculating the diff of entities failed due to search identifier in relation mapping
Why - Calculating the entities diff was using the entity relations to map its relations and whether to delete it. When using search identifier feature the entity contained the search query rather than the actual relation of the entity after creation.
How - Changed to use the entity created from port rather than the entity generated after JQ. Collecting the created entity returns the resulted relations identifiers that were generated for the entity.
Fixing:
```
> File "/usr/local/lib/python3.11/site-packages/port_ocean/core/event_listener/once.py", line 56, in resync_and_exit
await self.events["on_resync"]({})
File "/usr/local/lib/python3.11/site-packages/port_ocean/core/integ …
```
=> [Core] Fix resync issue when using `search identifier` in relation schema

.github/workflows/release-integrations.yml, integrations/gcp/CHANGELOG.md, integrations/gcp/gcp_core/search/iterators.py, integrations/gcp/gcp_core/search/resource_searches.py, integrations/gcp/gcp_core/search/utils.py, integrations/gcp/pyproject.toml
**What** - Added rate limit retry and backoff strategy to when searching for resources that the caller has `cloudasset.assets.searchAllResources`
**Why** -  GCP throws a 419 rate limit error which prevents resources from getting synced to port. Maximum Quota that can be set on GCP for cloud asset API calls is 400, to exceed that users are required to apply for higher quota.  
**How** - By leveraging the inbuilt support for Retry, we are able to implement an exponential backoff strategy for rate limit handling. 
=> [Integration][GCP] | Improved rate limit handling

CHANGELOG.md, port_ocean/core/event_listener/kafka.py, pyproject.toml
- **fix: kafka listener constant resync loop**
- **feat: bump version**
*Bugfix*
```diff
! What - Fix kafka listener never ending loop of resyncs bug
- Why - This bug was created when we started to updated the resyncState along with integration data,
- therefor each update would create a new audit-log change which triggered the Kafka listener to start a new resync
+ How - we validate that it was not an update created by the resyc-state by comparing them
```
=> fix resync-state kafka listener bug

Makefile, poetry.lock, port_ocean/cli/commands/new.py, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/.env.example, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/.port/resources/blueprints.json, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/.port/resources/port-app-config.yml, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/.port/spec.yaml, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/CHANGELOG.md, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/CONTRIBUTING.md, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/Makefile, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/changelog/.gitignore, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/main.py, port_ocean/cli/cookiecutter/{{cookiecutter.integration_slug}}/pyproject.toml, port_ocean/config/settings.py, pyproject.toml
* Proper `.env.example` files
* Update vscode launch configuration with new generated integration
* Add initial static examples to see the integration quickly in Port,
including example blueprints and mappings
* Add unit test stub
Update the cookiecutter template for new integrations with integration standards.
In addition, make it simpler to start developing an integration with a "working" sample out of the box.
=> Update cookiecutter to integration standards

.idea/watcherTasks.xml, CHANGELOG.md, port_ocean/clients/port/mixins/entities.py, pyproject.toml
What - Refer to entity in upsert entity response
Why - Response from upsert entity api isn't processed right and causes ocean core to use the raw entity that contains dict typed relation instead of string which is the relation's entity identifier
How - Simply refer to the entity key in a response that looks like {ok: true, entity: {...}}
=> [Framework] Refer to entity in upsert entity response

integrations/aws/CHANGELOG.md, integrations/aws/integration.py, integrations/aws/pyproject.toml
What - rename type
Why - wrong class name
How - rename the class
=> [Integration][AWS] fix integration config class name

integrations/sonarqube/CHANGELOG.md, integrations/sonarqube/client.py, integrations/sonarqube/main.py, integrations/sonarqube/pyproject.toml
What - The integration was throwing an error where the `self.metrics` was not found in the `get_all_sonarqube_analyses`(). This was because each resync handler creates a new instance of the sonarQube client, causing the client to lose the state of it's saved variables. An example is when the self.metrics in the previous handler is lost in subsequent clients. 
Why - Affecting the ingestion of onprem analysis kind as it relies on the metrics
How - Implemented a singleton pattern where we use one global instance of the sonarQube client across the application
=> [Integration][Sonarqube] - Fix sonarQube client has no attributes metrics

CHANGELOG.md, port_ocean/ocean.py, pyproject.toml
Since running on new event loops got us Semaphore is bound to a different event loop error
What - fix `Semaphore is bound to a different event loop`
Why - all Semaphore were used in different event loops and once the thread ended the Semaphore could not run in a different event loop
How - use the same event loop across all threads
=> [Integration][AWS] use the same event loop for all threads

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, port_ocean/clients/port/mixins/entities.py, pyproject.toml
What - Refer to entity key in upsert entity response, if the response is not 200 then turn raw search relations into None to not harm the deletion proccess
Why - Response from upsert entity api isn't processed right and causes ocean core to use the raw entity that contains dict typed relations instead of string which is the relation's entity identifier
How - refer to the entity key in a response that looks like {ok: true, entity: {...}}, if the response is not 200 turn the dict typed relations into None 
Provide links to the API …
=> [Framework] Fix bug search relation error unhashable dict

integrations/azure-devops/.port/resources/port-app-config.yaml, integrations/azure-devops/CHANGELOG.md, integrations/azure-devops/azure_devops/client/azure_devops_client.py, integrations/azure-devops/pyproject.toml
**What -**
This PR addresses a few bugs and improvements in the Azure DevOps (ADO) integration related to the default mappings for service and work-item entities, handling of project data, and logging enhancements.
**Why -**
- The original default mapping for services caused errors when repository names contained special characters like parentheses. The error prevented the repositories from being imported into Port.
- The work-item mapping had an issue where the relation to the project was incorrectly based on `System.TeamProject`, which referenced the project name instead of the internal project identifier
- It was necessary to update the mapping so that full project data, not just the project ID, is passed to the work-item entities
- Additionally, to aid in debugging and monitoring, …
=> [Integration][ADO] Bug Fix: Default mapping errors

CHANGELOG.md, port_ocean/core/integrations/mixins/sync_raw.py, port_ocean/ocean.py, pyproject.toml
What - Fix overriding of next resync status when cancelled due to scheduled resync
Why - When setting up a low resync interval and the resync still runs, the new resync sends an abort signal to the existing integration causing it to stop, which then the integration updates the integration as completed, while the integration is actually running a resync, this causes incorrect status in the UI. In the case of having kafka configured it can also cause the integration to detect new resync.
How - Handled `asyncio.CancelledError` and skips updating the resync status.  
Include screenshots from your environment showing how the resources …
=> [Core] Fix overriding of next resync status when cancelled due to scheduled resync

integrations/aws/CHANGELOG.md, integrations/aws/pyproject.toml, integrations/aws/tests/test_sample.py, integrations/aws/tests/test_utils.py, integrations/aws/utils/misc.py
Fixes [PORT-10362](https://getport.atlassian.net/browse/PORT-10362)
Addresses an issue where the `is_access_denied_exception` function in the AWS integration could raise an `AttributeError` if `e.response` is `None`. The function now includes a check to ensure `e.response` is not `None` before attempting to access its keys.
- Added a check in `is_access_denied_exception` to ensure `e.response` is not `None` before accessing its keys.
[PORT-10362]: …
=> [AWS] Fix: Handle NoneType response in is_access_denied_exception

integrations/gitlab/CHANGELOG.md, integrations/gitlab/gitlab_integration/events/event_handler.py, integrations/gitlab/gitlab_integration/events/setup.py, integrations/gitlab/gitlab_integration/gitlab_service.py, integrations/gitlab/gitlab_integration/ocean.py, integrations/gitlab/pyproject.toml, integrations/gitlab/tests/gitlab_integration/test_gitlab_service_webhook.py
What - Added logs, pagination and async implementation to the GitLab integration
Why -
How -
=> [Integration][Gitlab] - Introduce Pagination and Run Code in Async

CHANGELOG.md, port_ocean/tests/utils/test_async_iterators.py, port_ocean/utils/async_iterators.py, pyproject.toml
What - Added a util `semaphore_async_iterator` to enable seamless control over concurrent executions per kind.
Why - Simplifies the process of implementing concurrent limit when streaming async tasks. Works magic with the existing `stream_async_iterators_task` util for concurrency control.
How - Utilized asyncio Semaphore context manager, works with Bounded and Non Bounded Semaphores
=> [Core] | Added util for concurrency control

.github/workflows/actions/build-docker-image/action.yml, .github/workflows/build-infra-images.yml, .github/workflows/ci.yml, .github/workflows/detect-changes-matrix.yml, .github/workflows/docker-images-security-scan.yml, .github/workflows/release-integrations.yml, integrations/_infra/Dockerfile.Deb, integrations/_infra/Dockerfile.base.builder, integrations/_infra/Dockerfile.base.runner
What -
Why -
Releasing integrations took over 2 hours (!)
=> [Infra] Introduced multi stage build for images to improve built time

integrations/sonarqube/CHANGELOG.md, integrations/sonarqube/client.py, integrations/sonarqube/pyproject.toml
What - Fixed a bug where SonarQube instances lower than 10.2 report a 404 error when retrieving issues
Why - This is because the issues list API on SonarQube was introduced in 10.2 and also as an internal API
How - Checking for the integration version and choosing the right API based on the integration version
[SonarQube issues list API](https://next.sonarqube.com/sonarqube/web_api/api/issues/list?internal=true)
=> [Integration][SonarQube] Bug | 404 response when querying SonarQube issues

.github/workflows/verify-pr-title.yml
What - Add CI workflow to make sure pr titles are following conventions
Why - To make sure they are following conventions
How - Added github workflow to validate on PR changes
=> [Infra] Add CI workflow to make sure pr titles are following conventions

CHANGELOG.md, integrations/fake-integration/main.py, integrations/fake-integration/pyproject.toml, port_ocean/ocean.py, pyproject.toml
What - Fix memory leak due to repetitive registration of FastAPI routes
Why - Constant memory leak when registering FastAPI routes
How - Run app setup just once
=> [Core] Fix memory leak due to repetitive registration of FastAPI routes

.github/workflows/docker-images-security-scan.yml, integrations/aws/CHANGELOG.md, integrations/aws/pyproject.toml, integrations/aws/utils/resources.py
**What:**
Fixed an issue where the integration would enter an endless loop upon encountering a permission error when querying resources in a particular region. The code now raises the permission error instead of skipping it, allowing downstream code to handle it appropriately.
**Why:**
Previously, when a permission error occurred, the integration skipped the error without proper handling, causing it to get stuck in an infinite loop. By raising the error, we ensure that the integration does not loop endlessly and that the error can be managed correctly by downstream processes.
**How:**
- Updated the error handling logic to raise the permission error instead of skipping it.
- Verified that downstream code is capable of handling the raised exception without adverse effects.
- Tested the …
=> [Integration][AWS] | Fix an issue where the integration enters an endless loop on region permission error 

port_ocean/clients/port/utils.py, port_ocean/helpers/retry.py
What - I updated the retry mechanism to ensure the total retry time is capped at 5 minutes, with a maximum backoff time of 5 minutes between retries.
Why - This change is needed to handle the reduced port rate limit in integrations more effectively, minimizing the risk of overwhelming the system while still ensuring retries are reasonable.
How - I adjusted the retry logic to distribute retries over the 5-minute window, scaling backoff times to align with the reduced rate limit without exceeding the time limit.
Provide links to the API …
=> [Core] Support the reduction of Port rate limit in the integrations

.github/workflows/core-test.yml, .github/workflows/perf-test.yml, Makefile, integrations/jira/.port/resources/port-app-config.yaml, port_ocean/tests/helpers/fake_port_api.py, scripts/run-local-perf-test.sh
Add an opt in way to mock the port-api when running perf tests
In addition, add an opt in way to control the log level
=> [Core] Add optional mock port api for perf tests

CHANGELOG.md, integrations/jira/.port/resources/port-app-config.yaml, port_ocean/clients/port/authentication.py, port_ocean/clients/port/mixins/entities.py, port_ocean/helpers/retry.py, pyproject.toml
What -
1. Update the condition upon which the JWT token is refreshed so it will refresh on expiration instead of only after.
2. Set upsert entenies as retryable.
3. Remove timeout in favor of global timeout.
4. Update `handle_request` to use method for identifying retryable requests.
Why -
User receives 401 errors because JWT is expired so entities are not inserted.     
=> [Core] Change token refresh condition and retry upserts

CHANGELOG.md, port_ocean/core/handlers/entity_processor/jq_entity_processor.py, port_ocean/tests/core/handlers/entity_processor/test_jq_entity_processor.py, pyproject.toml
What -
added test and support for use-case of empty string of identifier/blueprint values, 
added debug log to validate the identifier and blueprint values
Why -
I've identified that there are 2 main use-cases for us to log the details about, for null, missing and / or mis configured values
AND for empty strings. 
the empty string is not a "wrong / misconfigured" value for JQ, but it is a non valid identifier. 
current logs were missing this details and were not clear enough
also added example on how to assert on logs
How -
added tests and validations following logs investigations
```
raw_results: list[dict[Any, Any]] = [
{"foo": "", "bar": "bluePrintMapped"},
{"foo": "identifierMapped", "bar": ""},
]
result = await mocked_processor._parse_items(mapping, raw_results)
assert "identifier" …
```
=> [Core] JQ Mapping log enrichment - empty values support

CHANGELOG.md, port_ocean/core/handlers/entity_processor/jq_entity_processor.py, port_ocean/tests/core/handlers/entity_processor/test_jq_entity_processor.py, pyproject.toml
What -
- Adjusted log teminology
- Faild transformations counter increments for all cases (None (null / missing), empty)
Why -
the terminology of the log was not clear enough
=> [Core] Adjust jq mapping log - terminology and counter

CHANGELOG.md, port_ocean/core/integrations/mixins/sync_raw.py, port_ocean/tests/core/handlers/mixins/test_sync_raw.py, pyproject.toml
What - Fixed a bug effecting live events handling
Why - There was a bug in the `register_raw` and `unregister_raw` that didn't handle correctly the response type from the `_register_resource_raw` and `_unregister_resource_raw` response which was changed in #1265 
How - Added handling for that new response type and added tests
=> [Core] Fix event handling when using `register_raw` and `unregister_raw`

CHANGELOG.md, port_ocean/core/integrations/mixins/sync_raw.py, pyproject.toml
What - improvements to reduce port's load
Why - to make the query easier for port
How - added blueprint to the search query
=> [Core] Fixed query to make the search easier on port's side

CHANGELOG.md, port_ocean/core/integrations/mixins/sync_raw.py, pyproject.toml
What - improvements to reduce port's load
Why - to make the query easier for port
How - fixed the identifier rule to be one
=> [Core] Fixed query to make the search easier on port's side - second improvement

CHANGELOG.md, port_ocean/context/event.py, port_ocean/core/handlers/port_app_config/api.py, port_ocean/exceptions/api.py, port_ocean/tests/core/handlers/port_app_config/test_api.py, port_ocean/tests/core/handlers/port_app_config/test_base.py, pyproject.toml
What - raise error if integration gets empty config from port 
Why - to avoid integration to delete entities if resync gets 0 entities 
How - raise error
=> [Core] Raise error if integration gets empty config from port 

integrations/sonarqube/CHANGELOG.md, integrations/sonarqube/main.py, integrations/sonarqube/pyproject.toml
What - Fix SonarQube reysnc bug where entities are deleted. This is a replacement of #1340.
Why - It causes users to lose data
How - Changing the way the `SonarQubeClient` is initialized
=> [Integration][SonarQube] Bug | Subsequent resync in SonarQube causes deletion of entities

CHANGELOG.md, port_ocean/cli/commands/defaults/clean.py, port_ocean/clients/port/mixins/integrations.py, port_ocean/core/defaults/clean.py, pyproject.toml
What  
- Added support for complete removal of an integration in the `ocean defaults clean` command.
- Introduced a new flag `--destroy` to enable full deletion of the integration
Why  
- Previously, the command only cleaned up the default blueprint and associated data but did not allow full removal.
- This enhancement provides users with a way to completely delete an integration during development
How  
- Updated the command logic to handle the `--destroy` flag.
- Ensured `--destroy` removes all integration-related configurations.
<h4> All tests should be run against the port production environment (using a testing org). </h4> …
=> [Core] Added flag to destroy integration config while running clean defaults cli command

CHANGELOG.md, port_ocean/clients/port/mixins/integrations.py, port_ocean/core/defaults/initialize.py, pyproject.toml
* Solve race condition when Port creates the integration config
* Check if integration is enabled for port provisioning if flag is set
=> [Core] Validation provision enabled for integrations

CHANGELOG.md, port_ocean/ocean.py, pyproject.toml
What - changed log level
Why - Readability of the code
How - changed log level
=> [Core] Changed log level

integrations/gitlab/CHANGELOG.md, integrations/gitlab/gitlab_integration/core/utils.py, integrations/gitlab/pyproject.toml, integrations/gitlab/tests/gitlab_integration/test_core/test_utils.py
What - Fixed a bug where glob patterns with slashes are not matched against bare file names such as `**/port.yml` pattern not matching `port.yml`.
Why - This is due to the way `fnmatch` handles matching without handling possible leading slashes in file names
How - Reimplemented the `does_pattern_apply` matching logic 
=> [Integration][GitLab] Bug | GitOps in GitLab Integration - Failure to map port yml file

CHANGELOG.md, port_ocean/core/defaults/initialize.py, pyproject.toml
What - fixed wrong integration version showing in UI and API
Why - we did not patch the integration when `OCEAN__INITIALIZE_PORT_RESOURCES=false`
How - moved the check of `OCEAN__INITIALIZE_PORT_RESOURCES=false` to after the patch
=> [Core] Wrong integration version showing in UI and API fix

integrations/bitbucket-cloud/CHANGELOG.md, integrations/bitbucket-cloud/bitbucket_cloud/helpers/file_kind_live_event.py, integrations/bitbucket-cloud/pyproject.toml, integrations/bitbucket-cloud/tests/webhook/processors/test_file_webhook_processor.py
What -
- Fixes bug in file kind live event where tracked files don't get upserted to port 
- Fixes a bug in File kind live events where files deleted from the bitbucket-cloud repository were not being properly unregistered (deleted) from Port. The webhook processor now correctly builds a minimal entity for deleted files, ensuring they are removed from Port when deleted in the source repository.
Why -
- The `get_file_paths` function was failing when `diff_stat.get("old")` or `diff_stat.get("new")` returned `None`, causing `NoneType` object has no attribute `get` exceptions that prevented file processing entirely
- Previously, when a file was deleted in bitbucket-cloud, the corresponding entity was not always removed from Port due to incomplete or missing entity construction for deletions. …
=> [Integration][bitbucket-cloud] Ensure Files Are Properly Deleted in Port For File Kind Live Events

integrations/argocd/.env.example, integrations/argocd/CHANGELOG.md, integrations/argocd/client.py, integrations/argocd/main.py, integrations/argocd/pyproject.toml, integrations/argocd/tests/test_client.py, integrations/argocd/tests/test_sample.py
…s` from API
What
Added null check for application resources from the ArgoCD API
Why
This provides a better null safety check to resolve issues arising from null values being returned for the resources queried.
How
Implemented a check against instances where:
* `applications` is `None`
* `application` has missing `metadata.uid` field
___
Bug fix
___
- Fixed null value iteration errors in ArgoCD deployment history and Kubernetes resources
- Added comprehensive test …
=> [Integration][ArgoCD] Iteration over Null Values Breaking ReSync

integrations/sentry/CHANGELOG.md, integrations/sentry/clients/sentry.py, integrations/sentry/pyproject.toml
A recent upgrade to HTTPX 0.28.1 introduced a behavioral change that overwrites existing query-string parameters whenever a separate params= argument is supplied. Any of our integrations that rely on the full “next” URL returned by the upstream API now request the first page in a loop until they exhaust the provider’s rate-limit.
What
Why
How
- Reset `params` to `None` after fetching paginated data.
___
Bug fix
___
- Fix pagination bug in Sentry integration caused by …
=> [Integration][Sentry] Pagination BugFix

.github/workflows/claude-generic.yml
What -
Why -
How -
___
Other
___
- Remove WebFetch tool from allowed_tools in Claude workflow
___
```mermaid
flowchart LR
A["Claude Workflow"] -- "remove" --> B["WebFetch Tool"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>claude-generic.yml</strong><dd><code>Remove WebFetch …
=> chore: fix permissions

.github/workflows/claude-generic.yml, CHANGELOG.md, port_ocean/clients/port/mixins/integrations.py, port_ocean/core/handlers/resync_state_updater/updater.py, port_ocean/core/integrations/mixins/sync_raw.py, port_ocean/core/integrations/mixins/utils.py, port_ocean/helpers/metric/metric.py, pyproject.toml
What - fixed 2 major bugs - reconciliation stuck on pending & the entire state of resync being wrong. also updated the post of reconciliation phase. 
Why - in port, the ui showed wrong data and mismatch between parts of the tab
How - not cleaning the dir after each subprocess ends, adding more reports of the metrics and fixing the state of the resync kind
___
Bug fix
___
- Fixed reconciliation metrics not updating properly during sync
- Added proper `__runtime__` metrics reporting for sync states
- Removed premature cleanup of Prometheus metrics after subprocess finish
- Enhanced sync state tracking across different phases
___ …
=> [Core] Fixed reconciliation bug & __runtime__ metrics reporting

.github/workflows/apply-release.yml, .github/workflows/build-infra-images.yml, .github/workflows/ci.yml, .github/workflows/claude-generic.yml, .github/workflows/claude-tag.yml, .github/workflows/core-test.yml, .github/workflows/create-new-sonarcloud-project.yml, .github/workflows/detect-changes-matrix.yml, .github/workflows/docker-images-security-scan.yml, .github/workflows/integrations-test.yml, .github/workflows/lint.yml, .github/workflows/perf-test.yml, .github/workflows/release-framework.yml, .github/workflows/release-integrations.yml, .github/workflows/sonarcloud-framework.yml, .github/workflows/sonarcloud-integrations.yml, .github/workflows/trigger-doc-sync.yml, .github/workflows/upgrade-integrations.yml, .github/workflows/validate-integration-files.yml, .github/workflows/verify-docs-build.yml
Other
___
- Upgrade `actions/checkout` from v4 to v5 across all workflows
- Update 22 GitHub Actions workflow files
___
```mermaid
flowchart LR
A["GitHub Workflows"] -- "upgrade" --> B["actions/checkout@v5"]
A -- "from" --> C["actions/checkout@v4"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><details><summary>20 files</summary><table>
<tr>
<td><strong>apply-release.yml</strong><dd><code>Upgrade checkout action to v5</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a …
=> [CI] update .gitignore and upgrade actions/checkout to v5 in workflows

integrations/aws-v3/.port/spec.yaml, integrations/aws-v3/CHANGELOG.md, integrations/aws-v3/aws/auth/providers/assume_role_with_web_identity_provider.py, integrations/aws-v3/aws/auth/session_factory.py, integrations/aws-v3/aws/auth/strategies/multi_account_strategy.py, integrations/aws-v3/aws/auth/strategies/organizations_strategy.py, integrations/aws-v3/aws/auth/utils.py, integrations/aws-v3/pyproject.toml, integrations/aws-v3/tests/auth/test_providers.py, integrations/aws-v3/tests/auth/test_session_factory.py, integrations/aws-v3/tests/auth/test_strategies.py, integrations/aws-v3/tests/conftest.py
- **[Integration][AWS-v3] Update AWS Account Role configuration in spec.yaml**
- **feat: Enhance AWS Account Role configuration in spec.yaml**
- **refactor: Update ResyncStrategyFactory to use account_role_arns**
- **feat: Introduce AWSOrganizationsNotInUseError for better error handling**
- **fix: Update healthcheck method to use account_role_arns**
- **refactor: Improve account role ARN handling in AssumeRoleWithWebIdentityProvider**
- **refactor: Revise AWSOrganizationsNotInUseError for clarity**
- **refactor: Update account role ARN handling across tests**
This PR implements a new organizations-first strategy for the AWS v3 integration that automatically attempts to use AWS Organizations for account discovery, with graceful fallback to single account mode when organizations is not …
=> [Integration][AWS-v3] convert to use organizations strategy by default

integrations/dynatrace/CHANGELOG.md, integrations/dynatrace/client.py, integrations/dynatrace/pyproject.toml, integrations/dynatrace/tests/test_client.py
What - `filter` key can sometimes be an empty string, don't fetch related slo entities when this is the case.
Why - The current fix correctly prevents the resulting error from crashing the resync. However, it's better if the errors do not occur in the first place. The customer is also still complaining because of the request failures.
How - Take out SLOs without a filter from the list of entities we want to fetch related entities for. 
- [ x ] Bug fix (non-breaking change which fixes an issue)
Provide links to the API documentation …
=> [Integration][Dynatrace] Don't fetch related entities for SLOs without a filter

CHANGELOG.md, port_ocean/clients/port/mixins/integrations.py, pyproject.toml
What - Change extractionTimestamp from string to int
Why - To make a unified template for timestamps
How - Cast to int
=> [Core] Change extractionTimestamp from string to int
